### ISSUE TITLE
Enable ReactiveCommand to be created with an observer for exceptions.

### ISSUE THREAD

**Issue by mteper** [reactiveui/ReactiveUI#1026]
Today, creation of a `ReactiveCommand` is typically a two-step affair: first you create a command, then you wire up exception handling for the `ThrownExceptions` observable. This is fine for one-off commands, and even for commands defined in same scope, where you can wire things up one at a time or in bulk (by merging `ThrowExceptions` streams from multiple commands), but it doesn't work for more complex scenarios (for example, where you want to handle exceptions in the same way across a view model and it's sub VMs).

Proposal: come up with a way to enable an optional `IObserver` or `Subject` argument to be passed in when creating a command that will replace the default `ThrownExceptions` subject for that command.

Example:

``` cs
var exceptionsSink = new Subject<Exception>();
exceptionSink.Subscribe(ex => Console.WriteLine(ex));

this.Command1 = ReactiveCommand.Create(/* ... */, exceptionObserver: exceptionSink);
this.Command2 = ReactiveCommand.CreateFromTask(/* ... */, exceptionObserver: exceptionSink);
```

**Comment by pmbanka** [comment]
I might be missing something obvious, but how does you example differ from the code below?
```
var exceptionsSink = new Subject<Exception>();
exceptionSink.Subscribe(ex => Console.WriteLine(ex));

this.Command1 = ReactiveCommand.Create(/* ... */);
this.Command1.ThrownExceptions.Subscribe(exceptionsSink);
this.Command2 = ReactiveCommand.CreateFromTask(/* ... */);
this.Command2.ThrownExceptions.Subscribe(exceptionsSink);
```
Well, except for being two lines shorter :)

**Comment by mteper** [comment]
@pmbanka as I said, the benefit is derived in complex scenarios. My example was oversimplified just to illustrate the syntax I had in mind.

**Comment by pmbanka** [comment]
@mteper I would really appreciate if you posted (maybe gist?) an example of such a complex scenario, where the change you propose would make a big difference. Right now I simply don't see the advantage you are talking about (or why the current mechanism "doesn't work").

The difference I can see is that `ThrownExceptions` schedules the errors to the UI thread, and providing your own `Scheduler` might bring some minor performance improvement in some cases, but I guess it's not what you had in mind.

**Comment by mteper** [comment]
OK, let me start off by clarifying that I don't think anything is broken in current RxCmd and what I am proposing is nothing more than syntactic sugar. Imagine this scenario:

We have a ViewModel that needs to do it's own thing for all command exceptions. That VM has a dozen commands, and a List of child view models, each with several commands. We want the `ThrownExceptions` observable streams from all of these tied into the same implementation. Now, it *can* be done with RxCmd as it is, but we can safe quite a few lines of code and hoop jumping if we can create and pass a single observer around. I think.

**Comment by kentcb** [comment]
@mteper I think I get what you're saying, and I can see how a constructor arg would save on some typing. However, I do have strong reservations about complicating an already busy API for the sake of an edge case.

Presumably the behavior of "do its own thing for all command exceptions" can be captured in a type?
```cs
public class MySpecialCommand<TParam, TResult> : ReactiveCommand<TParam, TResult>
{
    public MySpecialCommand(...) : base(...)
    {
        ThrownExceptions.Subscribe(ex => /* do something special */);
    }
}
```
Then all VMs that require this special behavior could create `MySpecialCommand` instances? I realize this means a different way of creating commands for that case (i.e. not using a factory), but what I'd argue is that you could always create your own factory method, or live with the fact that it's different because of the special requirements.

Here's the thing: even if we _did_ have an overload that allowed you to pass through an exception observer, you've in no enforced that child view models use that overload. At least with a custom type you have the options for enforcing this behavior (e.g. by defining a base class for the VMs with abstract properties of type `MySpecialCommand`).

Again, I am not saying we should definitely not add an exception observer parameter to command creation overloads. I'm just not convinced (yet) that the trade-off between API complexity and API utility warrants it.

**Comment by pmbanka** [comment]
Agree with @kentcb on this one. Additionally, if you have a lot of code that would be improved by your proposal, you can always roll out your own extension factory methods, or some kind of fluent `RxCmd<Tin, Tout> WithExceptionsOn<Tin, Tout>(this RxCmd<Tin, Tout> self, IObserver obs)` method.

**Comment by moswald** [comment]
So here's my issue: we should be championing Best Practices, and one best practice is One Step Initialization.

We can talk about it in the docs, we can add debug logging messages that are emitted when an exception is thrown but not caught, and we can patiently explain it to everyone who visits the Slack channel, but what we can't do is make `ThrownExceptions` more discoverable. People don't always remember everything they read in the docs, debug messages get missed (or worse, don't get triggered until in the hands of the user), and not everyone who uses RxUI has joined Slack.

Additionally, even if you _do_ know about `ThrownExceptions`, it's still too easy to write the following:

```
var exceptionsSink = new Subject<Exception>();
exceptionSink.Subscribe(ex => Console.WriteLine(ex));

this.Command1 = ReactiveCommand.Create(/* ... */);
this.Command2 = ReactiveCommand.CreateFromTask(/* ... */);
this.Command3 = ReactiveCommand.CreateFromTask(/* ... */);
this.Command1.ThrownExceptions.Subscribe(exceptionsSink);
this.Command3.ThrownExceptions.Subscribe(exceptionsSink);
this.Command3.ThrownExceptions.Subscribe(exceptionsSink);
```

and never realize `Command2.ThrownExceptions` are being ignored due to a simple copy-pasta typo.

I'm all for adding another parameter to the creation methods that take an observer and apply it to the `ThrownExceptions` property automatically. If I _really_ had my way, it wouldn't even be optional, but I think that would probably introduce too much of an API change.

**Comment by kentcb** [comment]
Speaking of best practices :) here's a couple:

1. Don't handle exceptions unless you expect them and have some valid recourse. I think this holds true for exceptions stemming from commands too (and the docs include this statement).
2. Exercise expected scenarios with unit tests.

Following these best practices counters your argument because:

1. Forcing users to provide an error handler will result in situations where people just log or, worse, ignore the exception. Then they'll be hella confused when things go wrong and the problem is just swallowed.
2. Copy/pasta problems would be spotted during unit testing.

**Comment by moswald** [comment]
Your first point is perfectly valid, but only argues that the parameter should be optional. It's still a good idea to present the option to the user immediately, rather than expose a property as an afterthought. If it's there in the constructor or factory method, it's an indication to the user that This Is Important.

I don't find the argument "they should cover the code with unit tests" compelling, however. Not everyone is great at writing tests (I still work with people who roll their eyes at the concept, but that's a totally different subject). Hoping that they'll catch their coding mistakes by writing good tests only shifts our obligation to teach RxUI onto them. (It also doesn't help the person who didn't realize `ThrownExceptions` even exists.)

**Comment by kentcb** [comment]
> it's an indication to the user that This Is Important

I guess that's where our opinions differ. Why do I think it's not important enough to warrant this kind of prominence? For the same reason we don't have checked exceptions in .NET. And because when you don't have a `ThrownExceptions` subscription, RxUI does the Good and Proper Thing by drawing it to your attention and bringing your process down.

As for the tests argument, it isn't necessarily unit tests, but just exercising the code in whatever way you need to to tease out errors - even if it's running up the app in the simulator. Correct me if I'm wrong, but it sounds like you're blanket-applying a `ThrownExceptions` handler to _all_ commands. This, I would not advocate as a best practice because it obscures _unexpected_ exceptions.

**Comment by moswald** [comment]
> Correct me if I'm wrong, but it sounds like you're blanket-applying a `ThrownExceptions` handler to all commands.

No, I just want to make it more clear that it's an option, and promote its use.

**Comment by mteper** [comment]
This has been a good discussion. I was at first surprised with @kentcb's assertion that most apps should not even need to subscribe to `ThrownExceptions` but then I realized that the app we are developing is not like most apps. We are working with other people's code and other people's sometimes very odd and unexpected configurations. We started out with relatively little exception handling, exactly on the philosophy that it would be better to just take the app down. What we've found out over time is that developers invariably continue to surprise us by the varying ... ~~sh~~ things they do, and the various unusual configurations, and the various strange workflows, such that we have pretty much covered every single command now with a subscription to `ThrownExceptions` so that we can at least surface the odd error back to the user.

**Comment by kentcb** [comment]
Hi, my name's Kent and I managed to forget this discussion for well over a year :blush: 

@mteper I suspect a better approach in your case might be to change the default exception handler via `RxApp.DefaultExceptionHandler`. That way you can have your logic execute regardless of whether the developers remember to attach to `ThrownExceptions`.
