### ISSUE TITLE
Move away from code contracts, and define internal argument helper

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1036]
There are a few different places ([example](https://github.com/reactiveui/ReactiveUI/blob/rxui7-master/ReactiveUI/IReactiveObject.cs#L50)) where code contracts are being used, but mostly it's just throwing exceptions ([example](https://github.com/reactiveui/ReactiveUI/blob/rxui7-master/ReactiveUI/CommandBinding.cs#L311)).

I think it would be good to have a discussion to decide which we should use, and put it in writing in the contribution guide.
### UPDATE

So the consensus (from here and Slack discussion) is:
- move away from contracts (change existing usage to inline checks)
- define our own helper to deal with checking arguments
- update the contributions docs so we educate our community

**Comment by ghuntley** [comment]
CodeContracts includes a static checker which means contracts are checked at compile time for correctness. CodeContracts are not implemented in Mono/Xamarin. There was a GSOC project but it wasn't completed and didn't get merged.

https://github.com/mono-soc-2012/code-contracts-oleg

The static checker for CodeContracts has since been open-sourced but Xamarin Studio lacks integration:

https://bugzilla.xamarin.com/show_bug.cgi?id=8400
https://github.com/Microsoft/CodeContracts

I _like_ Code Contracts as contracts can be applied to a interface and all consumers of the interface will inherit the conditions:

https://stackoverflow.com/questions/12602495/using-code-contracts-with-generic-interface-with-type-condition

Apart from x-plat support one the biggest problems with Code Contracts is the developer experience is slow, really slow. Excruciatingly slow.

I maintain https://github.com/ghuntley/conditions which is a x-plat way to do `pre` and `post` check conditions but unfortunately it happens at run-time. 

All said and done, my recommendation is to :fire: CodeContracts and don't bother with Conditions (go for quality of unit tests instead)

**Comment by flagbug** [comment]
Basically what @ghuntley said :+1:

**Comment by aalmada** [comment]
I share @ghuntley 's opinion both on contracts and conditions.
Code Contracts has one more advantage that is they can be exported into the documentation.
You can vote for Code Contracts support on Xamarin at: https://xamarin.uservoice.com/forums/144858-xamarin-platform-suggestions/suggestions/7057541-support-for-invoking-code-contracts-tools

**Comment by shiftkey** [comment]
Yep, seconding everything that @ghuntley said...

**Comment by kentcb** [comment]
:+1: thanks for the input - have updated the issue title+description accordingly.

**Comment by shiftkey** [comment]
Yeah, while I loved the goal of Code Contracts The Project™ the fact that it's support is patchy - and the overhead adds significant friction - I think a simpler set of internal checks will be good enough here...

**Comment by aalmada** [comment]
I'm still an outsider here but I love the fluent syntax of @ghuntley 's conditions.

**Comment by ghuntley** [comment]
@aalmada I can't take credit for the API design. Steven van Deursen did the original version, as it's no longer maintained (last update 2011) I've taken over stewardship and updated it to use the new reflection API's/add support for PCL.

**Comment by aalmada** [comment]
Sorry to come back to this issue but the update mentions:

> define our own helper to deal with checking arguments

Why reinvent the wheel? 'Conditions' is done, stable, x-plat, available as a Nuget and maintained by a ReactiveUI team member: https://github.com/ghuntley/conditions
I'd like to add argument validation to my own contributions and I need to know how it should be done.
My two cents.

**Comment by dpvreony** [comment]
I'm a bit late to the party here. What you could do is have a middle ground

- Change the project settings for CodeContracts to custom (so you don't\can't use the rewriter)
- Don't have it set to run contract checks on the developers machine (if you so wish)
- Mark the custom validation logic with [ContractArgumentValidator] (https://msdn.microsoft.com/en-us/library/system.diagnostics.contracts.contractargumentvalidatorattribute) and [ContractAbbreviator] (https://msdn.microsoft.com/en-us/library/system.diagnostics.contracts.contractabbreviatorattribute)

At least this gives you the option to still use the static analysis on a dev machine \ ci build. The only thing you can't get around is the slowness\memory usage of the static analysis as to move the database it uses requires MS SQL with windows auth.
