### ISSUE TITLE
Some form of `CompositeDisposable` for `this.WhenActivated` would be a nice addition.

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1063]
Kent:
> I use `WhenActivated` these days (in iOS and XF): https://github.com/kentcb/WorkoutWotch/blob/master/Src/WorkoutWotch.UI/ExerciseProgramView.xaml.cs#L21
> `AddTo` is still super useful because the code is far more readable. I have a custom `WhenActivated` (https://github.com/kentcb/WorkoutWotch/blob/master/Src/WorkoutWotch.Utility/ReactiveUI/WhenActivatedExtensions.cs) that gives you a `CompositeDisposable` instead of an `Action<IDisposable>`, which means I can do:
```this.WhenActivated(
    disposables =>
    {
        this.Bind(…)
            .AddTo(disposables);
    });
```

Geoff: 
> `AddTo` makes it super explicit that resource will be disposed but it's not really needed right? It's being explicit to help the reader of the code understand what will happen?

Kent: 
> Exactly. I could also do it using the built-in `WhenActivated` like this:
```this.WhenActivated(
    d =>
    {
        d(this.Bind(…));
    });
```
I just find `AddTo` improves readability. And, frankly, makes it easier to write too.

Dennis:
> I've created an extension method called `DisposeWith(CompositeDisposable)` for this, I too think that this makes it easier to read/write

JCM:
> In a similar vain, we wrap the WhenActivated at a lower level and have a ILifetime construct instead and invoke our own virtual methods of Activated through which the ILifetime is passed in.

**Comment by pmbanka** [comment]
While we are at it, I think it is worth revisiting the [discussion that happened when `this.WhenActivated` was first introduced](https://github.com/reactiveui/ReactiveUI/pull/503). Turns out there were some complains about the readability of the feature from the beginning.

I think the most important idea in that discussion was the [one proposed by @Haacked](https://github.com/reactiveui/ReactiveUI/pull/503#issuecomment-33496862):

> I'm not suggesting that. Let's not push the method of activation to the consumer. Let's focus on providing an easy way to register things that is automatically handled when activation is supported.

>Underneath the hood, it could be the same approach. But for end users, it's much simpler.

>For example, what if we did this for all the bind methods (pseudocode)?

>```
public static void Bind(this whateverItIs, ....) {
   if whateveveritIs is ISupportsActivation then
      Bind this in a manner that doesn't leak
}
```

Maybe it's time to rethink this as well?

**Comment by moswald** [comment]
That's probably a breaking change, so if we're going to do it, we should do it when we move to v7 (ie, now).

**Comment by moswald** [comment]
`Bind` operates on an item that implements `IActivatable`, which means we can and should auto-dispose it. In many cases, this will render the whole `WhenActivated` block obsolete.

**Comment by moswald** [comment]
A quick search through one of my current projects shows that out of the 14 uses of `WhenActivated`, 8 of them could be dropped because I was only using it to dispose of my bindings.

_Also_, I found one view (there may be more?) that wasn't disposing the bindings. It's a minor pit of failure, but it's simple and painless to turn it into a pit of success.

**Comment by kentcb** [comment]
> this will render the whole WhenActivated block obsolete

There's still VM activation, as well as activation for scenarios other than binding.

**Comment by moswald** [comment]
Sorry, I meant _can_ render the whole block obsolete.
