### ISSUE TITLE
Testing mystery

### ISSUE THREAD

**Issue by twiernik** [reactiveui/ReactiveUI#1089]
So I had a situation which I cannot explain and I'm writing here so maybe someone will have an idea what was going on. 
I used Fixie to test my view model and I couldn't make it work. I even posted on stackoverflow because I thought I was doing something wrong. Eventually I used XUnit and everything started to work just like that. I recorded a gif http://i.giphy.com/3o7WTr3hskNLkViHPW.gif ~3MB It shows that running test from Visual Studio with Fixie test runner fails, then I install XUnit with package manager and again Fixie test fails. Then I run xunit test from resharper and code works. And finally I run Fixie test and suddenly it works. I've tried building from commandline with same results ( not working without xunit ). And by failing I mean Expenditure output property 'not working'. I switched to XUnit but still I have no clue what was going on. Any ideas?

**Comment by kentcb** [comment]
I am not familiar with Fixie, but this is almost _certainly_ because Splat is not detecting that you're running under a unit test when you run with Fixie, but it is when you use xUnit. As a result, when you run under xUnit, the `Expenditure` property will be automatically subscribed to, whereas running under Fixie it will not.

To verify, check the value of `Splat.ModeDetector.InUnitTestRunner()` from your running test in both environments.

**Comment by twiernik** [comment]
You are right :)

**Comment by ghuntley** [comment]
https://github.com/paulcbetts/splat/issues/131 has been opened upstream at Splat. @twiernik if you could submit a pull-request to splat that would be ace.

**Comment by dachowiec** [comment]
paulcbetts/splat#133
