### ISSUE TITLE
Does 6.5.0 Support Windows 10 UWP?

### ISSUE THREAD

**Issue by SheriSteeves** [reactiveui/ReactiveUI#1101]
The repository says it supports Universal Windows Apps but I cannot get it to work. I'm completely new to ReactiveUI so I may be doing something wrong that I haven't learned yet.

I tried to take the WPF sample from the documentation [Reactive UI 101](http://docs.reactiveui.net/en/getting-started/example.html) and port it to a UWP app. I have encountered the following two issues:

- typing in the search text doesn't trigger the search until I click away from the field.
- my listbox is never updated, but I can see my search results list is being populated.

See my question on Stackflow for more details: [ListBox not populated in UWP with ReactiveUI](http://stackoverflow.com/questions/36651504/listbox-not-populated-in-uwp-with-reactiveui). 

After beating my head against a wall, I have also tried building and running the UWP sample from December 2015 in the repository, [RxUI and UWP .Net Native Sample](https://github.com/moswald/RxUI-UWP-Sample). Again, I think that what I type into the text box was supposed to get reflected somewhere saying "you typed xyz last time" but I never see anything.

IS UWP even supported?

Thanks,

Sheri

**Comment by moswald** [comment]
Hi Sheri,

Feel free to join us in [Slack](https://github.com/reactiveui/reactiveui#slack) to chat about things.

Yes, 6.5 supports UWP, but the v7 beta will do a better job when it's finally released. For one thing, the Events package doesn't support UWP unless you do some work to build it yourself.

On to your specifics. UWP doesn't update `TextBox` bindings until the control loses focus. If you want that functionality (and who doesn't), you will need to switch to using the RxUI `Bind()` family. Instead of `<TextBox x:Name="SearchBox" Text="{x:Bind PageViewModel.SearchTerm, Mode=TwoWay}"/>`, place the following in your code-behind:

```
this.WhenActivated(d => {
    d(this.Bind(ViewModel, vm => vm.SearchTerm, v => v.SearchBox.Text));
});
```

It's generally recommended that you prefer to implement your bindings using `{x:Bind}`, but if that doesn't work for some reason, then to use `this.Bind` or `this.OneWayBind` instead of `{Binding}`.

As for your list population issue, I'm going to speculate that you are binding against a `List<T>` that gets replaced. Instead of doing that, try creating a single `ReactiveList<T>` that is cleared and repopulated. Then your `ListView` (switch to view, not box :) ) can bind it's `ItemsSource` property to that.

**Comment by SheriSteeves** [comment]
Matt, 

Thanks for the reply, and I've asked to be added to Slack. I have the sneaking feeling I'm going to doing a lot of reading and asking a lot of questions.

Thanks for heads up on the binding, and the thoughts on the list - it all makes sense. I was considering a listview and not box in my XAML as well.

New to UWP, XAML and ReactiveUI sometimes I don't even know where to start looking..

Do you have any ETA in the version 7 beta or prod?

**Comment by moswald** [comment]
No ETA at the moment, but you can follow along [here](https://github.com/reactiveui/ReactiveUI/pull/1092) and [here](https://github.com/reactiveui/ReactiveUI/pull/850).

**Comment by ghuntley** [comment]
@SheriSteeves we have a feed on MyGet for V7 which includes reactiveui-events for UWP and various other improvements. 6.5 works fine, one must be careful with reflection with dotnet native however (this is true for all frameworks/usage) and as such we recommend using `x:Bind` where possible. Come join us in Slack and you'll find the feed details in the channel topic.
