### ISSUE TITLE
ReactiveUI 7 - Using thrown exceptions to reinvoke a command breaks

### ISSUE THREAD

**Issue by dapullar** [reactiveui/ReactiveUI#1215]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I create an Reactive Command from an observable and subscribe to thrown errors, when I attempt to reinvoke the command to retry, the command just hangs

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```c#
public ReactiveCommand<Unit, User> UserCommand { get; set; }

public ProfileViewModel() {
	UserCommand = ReactiveCommand.CreateFromObservable(() => UserErrorTest());

	UserCommand.Subscribe(/* do something */);

	UserCommand.ThrownExceptions
	           .SelectMany(ex => Errors.Handle(ex))
		   .Where(recovery => recovery == ErrorRecoveryOption.Retry)
	           .Select(_ => Unit.Default)
		   .InvokeCommand(UserCommand);
}

public IObservable<User> GetUser() {
	var userService = new UserService();
	return userService.GetUser();
}

public IObservable<User> UserErrorTest() {
	return Observable.Create<User>(obs => {
		return GetUser().Subscribe(user => {
			if (new Random().Next() % 2 == 0) {
				obs.OnNext(user);
			} else {
				obs.OnError(new Exception("failed"));
			}
		}, obs.OnError, obs.OnCompleted);
	});
}
```

**What is the expected behavior?**
When retry is returned from the interaction, it should re invoke the command. The same way it would work in rxui-6.

**What is the motivation / use case for changing the behavior?**
The command ceases to work once OnError is called.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI?**

Became a problem in rxui-7 worked perfectly with UserError in rxui-6 as well as with the legacy package with interactions.

**Comment by kentcb** [comment]
As a result of #1143, `InvokeCommand` in RxUI7 now respects the execution window. That is, if the command is not executable when `InvokeCommand` is called, the request is silently dropped. Since the command is still in the process of dealing with the error, it's still technically executing at the time you're calling `InvokeCommand`, so your request is being dropped.

Two ways around this:
1. Stick in an `ObserveOn` before your `InvokeCommand` so that it's scheduled to run instead of running immediately. This will allow the command execution to finish before attempting re-invocation.
2. Don't use `InvokeCommand` and instead use `Execute`, which does not respect the execution window of the command.

**Comment by dapullar** [comment]
I see, makes sense. Yet if I try any of the methods that you are suggesting, the outcome is still the same. The command will fire once more, then begin to silently fail then after. I even tried to throttle until `CanExecute` is true but no luck.

```c#
UserCommand.ThrownExceptions
           .SelectMany(ex => Errors.Handle(ex))
	   .Where(recovery => recovery == ErrorRecoveryOption.Retry)
	   .Select(_ => Unit.Default)
	   .ObserveOn(RxApp.TaskpoolScheduler)
	   .InvokeCommand(UserCommand);
```

```c#
UserCommand.ThrownExceptions
           .SelectMany(ex => Errors.Handle(ex))
	   .Where(recovery => recovery == ErrorRecoveryOption.Retry)
	   .Select(_ => Unit.Default)
           .Subscribe(x => UserCommand.Execute(x));
```

**Comment by kentcb** [comment]
Whilst I haven't tried your specific repro (see mine below), there are problems with both the things you've tried. In the first, you must use the correct scheduler (`MainThreadScheduler`), otherwise you're not scheduling the work for _after_ the execution has finished. In the second, you're not subscribing to `Execute`, which is lazy (returns `IObservable<TResult>`).

Here's my repro, which works fine:

```C#
[Fact]
public void ExecutionCanBeImmediatelyTriedAgain()
{
    var count = 0;
    var fixture = ReactiveCommand.CreateFromObservable(
        () =>
            Observable.Create<Unit>(
                observer => {
                    if (count++ < 1) {
                        throw new InvalidOperationException();
                    }

                    observer.OnNext(Unit.Default);
                    observer.OnCompleted();
                    return Disposable.Empty;
                }));
    var executionCount = 0;

    // option 1
    fixture
        .ThrownExceptions
        .ObserveOn(RxApp.MainThreadScheduler)
        .Select(_ => Unit.Default)
        .InvokeCommand(fixture);

    //// option 2
    //fixture
    //    .ThrownExceptions
    //    .SelectMany(_ => fixture.Execute())
    //    .Subscribe();

    fixture
        .Subscribe(_ => ++executionCount);

    fixture
        .Execute()
        .Subscribe(
            _ => { },
            ex => { },
            () => { });
    Assert.Equal(1, executionCount);

    fixture
        .Execute()
        .Subscribe(
            _ => { },
            ex => { },
            () => { });
    Assert.Equal(2, executionCount);
}
```
