### ISSUE TITLE
ToProperty weirdness in 7.2.0

### ISSUE THREAD

**Issue by oliverw** [reactiveui/ReactiveUI#1297]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The value of OAPH based read-only properties is not available after the viewmodel constructor has been executed. This is a breaking change from 7.1.0. I'm not sure if this is related to #785.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```c#
public class RecordAudioViewModel : ReactiveObject
{
    public RecordAudioViewModel(IComponentContext ctx, ICoreStrings coreStrings)
    {
        recordButtonCaption = this.WhenAny(x => x.IsRecording,
                x => x.Value ? coreStrings.SaveButtonCaption : coreStrings.RecordButtonCaption)
            .ToProperty(this, x => x.RecordButtonCaption);
    }

    private readonly ObservableAsPropertyHelper<string> recordButtonCaption;

    public string RecordButtonCaption => recordButtonCaption.Value;

    private bool isRecording;

    public bool IsRecording
    {
        get { return isRecording; }
        set { this.RaiseAndSetIfChanged(ref isRecording, value); }
    }
}
```

Prior to release 7.2.0 the value of <code>RecordButtonCaption</code> was immediately available after constructing the viewmodel. After upgrading to 7.2.0 this is no longer the case and my application crashed in converter that didn't expect a null string reference.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

7.2.0. Worked with 7.1.0.

**Comment by kentcb** [comment]
Here's a copy-pastable repro (console app):

```C#
using System;
using ReactiveUI;

namespace ReproRxUI1297
{
    class Program
    {
        static void Main(string[] args)
        {
            var vm = new RecordAudioViewModel();
            Console.WriteLine(vm.RecordButtonCaption);
            Console.ReadKey();
        }
    }

    public class RecordAudioViewModel : ReactiveObject
    {
        public RecordAudioViewModel()
        {
            recordButtonCaption = this
                .WhenAny(
                    x => x.IsRecording,
                    x => x.Value ? "SAVE" : "RECORD")
                .ToProperty(this, x => x.RecordButtonCaption);
        }

        private readonly ObservableAsPropertyHelper<string> recordButtonCaption;

        public string RecordButtonCaption => recordButtonCaption.Value;

        private bool isRecording;

        public bool IsRecording
        {
            get { return isRecording; }
            set { this.RaiseAndSetIfChanged(ref isRecording, value); }
        }
    }
}
```
This app works exactly the same for me on both 7.1 and 7.2. And this is what I would expect given there were no changes to OAPH in 7.2

Perhaps there's something else going on?

**Comment by oliverw** [comment]
Hmm. I can repro this 100% of the time by just changing the RxUi Version from 7.1.0 to 7.2.0 in my project.json. I'm going to provide a more comprehensive example.

**Comment by kentcb** [comment]
Hmmm, you said project.json. I'm using VS2015. Any chance you have that lying around to try as well? Wondering if it comes down to tooling...

**Comment by oliverw** [comment]
Yeah I'm using VS 2015 as well. The viewmodel in question lives inside a .netstandard 1.3 PCL and is consumed by .Net 4.6.2 WPF App.

**Comment by Qonstrukt** [comment]
Can you show how you're accessing the `RecordButtonCaption` property after constructing the ViewModel?

**Comment by oliverw** [comment]
Through a very simple XAML binding:

```
<TextBlock x:Name="RecordButtonLabel" Margin="6, 0, 0, 2" Text="{Binding RecordButtonCaption, Converter={StaticResource TextCaseConverter}}">
</TextBlock>
```

**Comment by oliverw** [comment]
Ok, this is one of those moments in the life of a developer where you need a second pair of eyes. The problem is **indeed not related to RxUi 7.2**. Nonetheless I can't figure out why it happens. I've attached a minimal repro solution. If anyone could enlighten me as to why one of the buttons works while the other does not.

[RxUiRepro.zip](https://github.com/reactiveui/ReactiveUI/files/839661/RxUiRepro.zip)

**Comment by PureWeen** [comment]
Hmm that's an interesting one..  So I think it has to do with the timing and how ToProperty  isn't throwing a property changed event when its "initial" value gets set..

ToProperty uses a "CurrentThreadScheduler" to schedule itself so it's basically Queue'd to set that property. So right now the order of operations for the no work goes like this

-WhenAny Executes inside constructor
-ToPropery Subject is Queue'd on the MainThreadScheduler by CurrentThreadScheduler
-WPF component binds to a NULL value on the VM because the operation to set the value of ToProperty has been scheduled
-ToProperty is set but no PropertyChanged event fires because it's the initial value (bug?)   I verified this by subscribing to the VM's property changed handler and noticed that it never fires which I guess makes sense because in theory they are "initial values"

If you set the Scheduler on ToProperty to the ImmediateScheduler then it all works

**Comment by kentcb** [comment]
Thanks for the repro @oliverw.

It's a curious problem I've not encountered before. I can't dig too deep right now, but I can share my findings thus far...

It seems to be something to do with using `CurrentThreadScheduler` and `ShowDialog`. It's like `ShowDialog` is blocking the `CurrentThreadScheduler` from doing its work. This may well be fixed in Rx3, but I don't have time to verify.

I found two workarounds:

1. Explicitly specify the main scheduler on `ToProperty`
2. Use `Show` instead of `ShowDialog`

**Comment by oliverw** [comment]
@kentcb @PureWeen Thanks for your findings guys. I've also found out something. <code>RecordButtonCaption</code> is not even updating after the dialog has been opened and the OAPH input property is updated through a command. Bummer. I've updated the sample.

[RxUiRepro.zip](https://github.com/reactiveui/ReactiveUI/files/840370/RxUiRepro.zip)

**Comment by PureWeen** [comment]
Yea I'm pretty sure if you just let it play out the OPH essentially "breaks" because of how the Dialog seems to affect the scheduling.   @kentcb  had some good suggestions that should make it work for you or if you do something like this

```
 recordButtonCaption = this.WhenAny(x => x.IsRecording,
                    x => x.Value ? "foo" : "bar")
                .ToProperty(this, x => x.RecordButtonCaption, scheduler: System.Reactive.Concurrency.ImmediateScheduler.Instance);
```

that also works because then the ToProperty internally gets set immediately and has a value available to the initial binding operation opposed to getting queued later down the road

**Comment by oliverw** [comment]
@PureWeen Yeah I know Shane. I just wanted emphasize the seriousness of this issue. Closing this now.

**Comment by PureWeen** [comment]
Aw ok sorry about that.. I misunderstood the intention of your statement

**Comment by snalesso** [comment]
> Thanks for the repro @oliverw.
> 
> It's a curious problem I've not encountered before. I can't dig too deep right now, but I can share my findings thus far...
> 
> It seems to be something to do with using `CurrentThreadScheduler` and `ShowDialog`. It's like `ShowDialog` is blocking the `CurrentThreadScheduler` from doing its work. This may well be fixed in Rx3, but I don't have time to verify.
> 
> I found two workarounds:
> 
> 1. Explicitly specify the main scheduler on `ToProperty`
> 2. Use `Show` instead of `ShowDialog`

So is this a bug in Rx (and this is a workaround) or we are supposed to do this?

Thanks

**Comment by glennawatson** [comment]
Hi there,

We ask that you don't ask question on really old issues since it'd be likely the people involved will get notifications even if they haven't used the project in quite a while.

Best thing to do when you got questions about these older bugs is to, just jump on Slack https://reactiveui.net/slack or ask on stackoverflow.
