### ISSUE TITLE
ReactiveCommand as a cool way to call services in constructor!

### ISSUE THREAD

**Issue by helzgate** [reactiveui/ReactiveUI#1351]
I've found that calling services asynchronously in the constructor of a viewmodel is a big no-no, or at least there are a lot of caveats with difficult to understand examples on how to resolve them.  I've found that using ReactiveCommand for my async call in my constructors works great and as far as I can tell works for all use-cases I'm dealing with.  If this is in fact ok to use you guys need to be aware of this because it's AWESOME and others could benefit even if they don't use ReactiveUI in any other areas of their app!!!

Here is how I use it:

    using System;
    using System.Reactive;
    using ReactiveUI;
    using VoiceApp.Interfaces;
    using Xamarin.Forms;

    namespace VoiceApp.ViewModels
    {
        public class SomeViewModel : ReactiveObject
        {
		    ISpeakInterface mySpeak = DependencyService.Get<ISpeakInterface>();

		    private IWordsService _wordsService;
                    
                   // we will use ReactiveCommand to help us use a service in the constructor
                    private ReactiveCommand<Unit, string> CallService{ get;	set; }

		    public SomeViewModel(IWordsService wordsService)
		    {
			    _wordsService = wordsService;

                        // here is the magic!
		        CallService = ReactiveCommand.CreateFromTask(async _ =>
		        {
			       if (_wordsService == null)
				       throw new TimeoutException("Api Service is currently unavailable");

			       var result = await _wordsService.GetWordsToSpeak();
			       return result;
		        });

			    CallService.Execute().Subscribe(result =>
			    {
				    Device.BeginInvokeOnMainThread(() =>
				    {
					    mySpeak.MyStartSpeak(result); // see below
				    });

			    });

			    CallService.ThrownExceptions
			      .Subscribe(ex =>
			      {
				      //TODO: Notify user visually
			      });
		    }
        }
    }

**Comment by kentcb** [comment]
Bit confused by this. On the one hand you say:

> calling services asynchronously in the constructor of a viewmodel is a big no-no

But then you say:

> I've found that using ReactiveCommand for my async call in my constructors works great

Reading between the lines, are you in fact saying that you've been told or read somewhere that executing commands in your constructor is bad? If so, where?

**Comment by helzgate** [comment]
@kentcb Kent, according to articles like this: [article](https://forums.xamarin.com/discussion/28983/call-async-method-in-constructor) you shouldn't do work in a constructor.  There are workarounds of course but some of them require a lot of boilerplate or are hard to understand or don't fit exactly what I'm trying to do.  If you search around for "calling async methods in constructors" you will find many forums and stack overflow articles where people are struggling with this. 

One solution suggested calling async method in the page code-behind, but in my use case it can't be there, it has to be in the viewmodel constructor.  Another suggestion recommended a fire and forget approach but then you have to wire-up messaging between the service back to the viewmodel and although this works i'm tired of using messaging for absolutely everything.  I've even seen other methods like instantiating the viewmodel first in the code-behind then calling seperate init() methods on the viewmodel, ...no thanks.

What I was telling the folks at ReactiveUI is a lot of people are struggling with these workarounds with no solid solution on how to resolve this problem and I found that the best workaround I've seen is to use ReactiveUI's commands in the constructor, it works amazing and is simple and easy to understand and even allows for error handling.

**Comment by kentcb** [comment]
@helzgate I think there's a big difference between calling an `async void` or `async Task` method from a constructor versus subscribing to a reactive pipeline. In the former case, simply calling the method will cause a crash if an exception is raised because nothing has observed it. One can use `ContinueWith` to address this, but most people using TPL confine themselves to what can be achieved with an `await` and possibly the static methods on `Task`.

An Rx pipeline is different because handling errors is just a case of using the appropriate operator (e.g. `Catch` or `Retry`) and/or supplying a handler for any  exception when calling `Subscribe`. Of course, if you're using the TPL you can do a simple `ToObservable` call to turn a `Task<T>` into an `IObservable<T>`.

That said, instigating an asynchronous operation from a constructor might be ill-advised for other reasons. For example, if the view model represents an item in the list, you probably don't want to instigate 1000 asynchronous operations when you create 1000 view models to back your list. RxUI addresses this with its activation support. Activation essentially means "I'm on screen" and deactivation means "I'm off the screen".

View models can hook into activation just like views can. To do so, they're required to implement `ISupportsActivation`. Then they can use `WhenActivated` to start an asynchronous operation, which can also be cancelled proactively if the view model goes off screen (deactives) before the asynchronous operation completes.

```C#
public class VM : ReactiveObject, ISupportsActivation // implementation omitted because it's easy
{
    public VM()
    {
        this.WhenActivated(disposables =>
            {
                DoSomeAsync()
                    .ToObservable()
                    .Subscribe(
                        result => /* handle result */,
                        exception => /* handle error */)
                    .DisposeWith(disposables);
            });
    }
}
```

**Comment by helzgate** [comment]
@kentcb This is so good!  Thank you very much!
