### ISSUE TITLE
ReactiveCommand.ThrownExceptions not working as I expected

### ISSUE THREAD

**Issue by JoostOuweland** [reactiveui/ReactiveUI#1356]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
- There is a subscription to ThrownExceptions of a ReactiveCommand
- The command is executed
- Exception happens somewhere in observable chain of the command
- Application crashes

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```
var MyCommand = ReactiveCommand.CreateFromObservable(PerformCommand);
MyCommand.ThrownExceptions.Subscribe(OnMyCommandException);
MyCommand.Execute().Subscribe();

IObservable<Unit> PerformCommand() {
    return Observable.Throw<Unit>(new Exception("This should be caught"));
}

void OnMyCommandException(Exception exception) {
    Debug.WriteLine("Exception caught"); // Doesn't happen
}
```

**What is the expected behavior?**
Looking at the [documentation](https://docs.reactiveui.net/en/user-guide/commands/command-errors.html), it should be possible to just have a subscription to `ReactiveCommand.ThrownExceptions` and any exception occurring in the chain would be rerouted to the ThrownExceptions observer. Not crashing the application.

**What is the motivation / use case for changing the behavior?**
Either the documentation should be changed, or the implementation. So it is clear to the developer how to catch exceptions with commands.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
Tried with 7.0.0, 7.1.0, 7.2.0, 7.3.0 and 7.4.0 but no difference between those versions.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
2 workarounds:
- Use `Observable.Return(Unit.Default).InvokeCommand(MyCommand)`instead of `MyCommand.Execute().Subscribe()`
- Use `MyCommand.Execute().Subscribe(_ => { }, _ => { })`instead of `MyCommand.Execute().Subscribe()`

**Comment by davecader** [comment]
Having the same problem. If an exception is generated in the action that is invoked when you execute a command by calling Execute().Subscribe() explicitly then that exception will crash the application of be caught by the top level unhandled exception handler. This occurs regardless of whether or not you are subscribing to ThrownExceptions.

Replacing Subscribe() with Subscribe(_ => {}, _ => ()), as suggested, appeared to resolve the issue.

**Comment by Qonstrukt** [comment]
To clarify the situation, this is a quote from the specific part of the documentation:

> https://docs.reactiveui.net/en/user-guide/commands/command-errors.html
To address this dilemma, ReactiveCommand includes a ThrownExceptions observable (of type IObservable<Exception>). Any errors that occur in your execution logic will also tick through this observable. If you haven't subscribed to it, ReactiveUI will bring down your application. This forces you towards a pit of error-handling success.

The last sentence implies your application shouldn't crash if you do subscribe to `ThrownExceptions`. So either the documentation is unclear, or this isn't supposed to work like this.

I'm leaning toward the latter, but I'm not 100% sure. The fact calling `Execute` directly doesn't impose a check on `canExecute` as well is perfectly explainable. You're manually subscribing, so implying some onError handling there isn't that far fetched maybe. Although I don't think they're exactly the same situations.

**Comment by kentcb** [comment]
Just been looking into this. Turns out, the code already works as expected, and [here is the test](https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI.Tests/ReactiveCommandTest.cs#L520) that validates the relevant behavior.

I think the misunderstanding here is the expectation that a subscription to `ThrownExceptions` alleviates you of the need to manage individual pipelines produced by a call to `Execute`. I will clarify the documentation as best I can then update with a comment here.

Please re-open if you think I've misunderstood the situation here.

**Comment by kentcb** [comment]
Actually, I've been reading those docs and I feel like it's already pretty clear...? I mean, it obviously isn't because otherwise there wouldn't be confusion, but I guess I'm not sure how to make it clearer.

The key word, which is italicized, is _also_. In other words, the error will tick through both pipelines - the one you get back from `Execute` _and_ through to `ThrownExceptions`.

Let me pre-empty the obvious question: why not "swallow" the error so that the `Execute` pipeline never fails? This would not be a good idea because sometimes you want to react differently to individual executions of the command. If all you had was `ThrownExceptions` you have no way of knowing which individual execution of the command caused that exception.

Here's a concrete use-case: your VM needs to automatically invoke a command automatically every 3 minutes, but also in response to the user clicking a button in the UI. Any error from any invocation of the command should be logged, but only invocations instigated by the user should result in a message being displayed to them.

If `Execute` was to swallow errors, ReactiveUI would really be making things super hard for you here. You'd probably end up with an `Exception` subclass just so you can differentiate exceptions from the UI instigation from the automatic instigation. Not pretty.

On top of all this, you don't generally execute commands with `Execute`. That's the lowest-level mechanism. Normally you would use higher-level abstractions such as `BindCommand` and `InvokeCommand`, both of which deal with errors in the execution pipeline for you (by swallowing them, because it makes sense to do so there).

Can you guys give me feedback on the above:

1. Does it make sense now?
2. How could the docs be clearer?

Thanks!

**Comment by Qonstrukt** [comment]
It makes sense, and it's all clear, to me at least.
What threw me off initially was this line in the docs: 

> If you haven't subscribed to it, ReactiveUI will bring down your application.

So if you reverse this sentence, it implies your application shouldn't go down as long as you subscribe to this.

**Comment by qrzychu** [comment]
@kentcb In that case you would just use Subrcibe(_=>{}, yourErrorHandlerForThisSpecificCase);

In EVERY other situation you end up writing Subscribe(_=>{},_=>{}); instead of just Subscribe(); so that app does not crush. I know this is closed issue, but could you reconsider? 

I love reactiveui beacuse it allows me to easily do cool stuff, but this is just plain pain in the buttocks.

**Comment by Qonstrukt** [comment]
The point actually is not to use `Execute ()` yourself, unless you absolutely want to, because you want to do your own exception handling or ignore the canExecute logic.

In our own apps we found the need to use `Execute ()` pretty small anyway.

**Comment by qrzychu** [comment]
I use it mostly in views in WhenActivated to run command like GetData, which is pretty common scenario. What is the better way to do this?

**Comment by Qonstrukt** [comment]
When there is no observable sequence to chain onto, just create a new one:

`Observable.Return(Unit.Default).InvokeCommand(MyCommand);`

**Comment by kentcb** [comment]
@qrzychu Do you have any suggestion on how it should work? Per my previous comment, I can't see any alternative that doesn't prevent other important scenarios.

As for how to go about this, you have lots of options...

@Qonstrukt mentioned one, though it's not one I tend to use because it feels a little contrived to me.

Another option is to turn `WhenActivated` into a pipeline, which is something I often do via these extension methods:
```C#
public static IObservable<bool> GetIsActivated(this ISupportsActivation @this)
{
    Ensure.ArgumentNotNull(@this, nameof(@this));

    return Observable
        .Merge(
            @this.Activator.Activated.Select(_ => true),
            @this.Activator.Deactivated.Select(_ => false))
        .Replay(1)
        .RefCount();
}

public static IObservable<bool> GetIsActivated(this IActivatable @this)
{
    Ensure.ArgumentNotNull(@this, nameof(@this));

    var activationForViewFetcher = Locator.Current.GetService<IActivationForViewFetcher>();
    return activationForViewFetcher
        .GetActivationForView(@this)
        .Replay(1)
        .RefCount();
}
```
So now you can just do this:
```C#
this
    .GetIsActivated()
    .Where(x => x)    // I use a WhereTrue extension here instead, just for readability
    .InvokeCommand(...);
```
Yet another option is to define your own subscribe extension methods:
```C#
public static IDisposable SubscribeAndIgnoreError<T>(this IObservable<T> @this, Action<T> onNext) =>
    @this
        .Subscribe(
            onNext,
            _ => {});

public static IDisposable SubscribeAndIgnoreError<T>(this IObservable<T> @this) =>
    @this
        .Subscribe(
            _ => {},
            _ => {});
```
Now you can just:
```C#
this
    .ViewModel
    .MyCommand
    .Execute()
    .SubscribeAndIgnoreErrors();
```
As an aside, perhaps you should consider moving this logic into your VMs. VMs can also participate in activation, and it makes more sense to me for the VM to instigate loading the data.

Hope this helps.

**Comment by qrzychu** [comment]
I don't like VMs activating themeselves, becuasu then you have to mock everything in every unit test.

I ened up using exactly the same extension methos that @kentcb provided.
My thoughts are: if I need to take care of excpetion after this specific invocation, I can do that. But in 90% of situations that's not the case. 

The easiest solution would be to add those extensions into reactive-ui - that way old codebases don't need changes, and all new ones have a fast and simple way to start commands.

For me this trick with Observable.Return feels like cheating, but it also works. One thing for sure, documantation needs to EXPLICITLY say that you need excpetion handler for Subrscribe() after command.Invoke(), because ThrownExceptions is not enough.
Other thing, there should be sample with Observable.Return as alternative way to just lunch command.

**Comment by JFMG** [comment]
It's an old topic but I'd like to give my simple solution to this topic, in case other people are still having this problem and coming to this site. You can just use `Catch`, if you execute a command directly. Then the exception will get caught and your ThrownExceptions subscription still works.

So instead of writing
`await MyCommand.Execute()` or `MyCommand.Execute().Subscribe()`
you should write
`await MyCommand.Execute().Catch(Observable.Return(Unit.Default))` or `MyCommand.Execute().Catch(Observable.Return(Unit.Default)).Subscribe()`

In my example I don't have a return type for my command, but if you got one, you can return what you need, like this:
`int number = await MyCommand.Execute().Catch(Observable.Return(-1))`
In case of an exception `number` will be -1 and there won't be any crash.
