### ISSUE TITLE
Remove InvokeCommand overrides with ICommand

### ISSUE THREAD

**Issue by thedillonb** [reactiveui/ReactiveUI#1374]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`InvokeCommand` currently takes a `ICommand` or a `ReactiveCommandBase<TParam, TResult>`. Unfortunately, as all `ReactiveCommand` objects implement `ICommand` it becomes problematic when you `InvokeCommand` a `ReactiveCommand` that has mismatched input parameters.

**What is the expected behavior?**
This should easily be a compile time check but since `ReactiveCommand` extends from `ICommand` it falls back to that method override and provides no static time checks. Then, when you run the app and a input of `bool` invokes a command with a `TParam` of `Unit` the app crashes :/

**What is the motivation / use case for changing the behavior?**
Better experience with ReactiveUI.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
Latest: 7.4.0.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by kentcb** [comment]
I sympathise with what you're saying, but two points:

1. removing the overload means there is no way to `InvokeCommand` against a non-reactive command. That would be a big breaking change.
2. the crash you get when the types mismatch results in a very clear and concise message telling the developer exactly what they've done wrong: `Command requires parameters of type {0}, but received parameter of type {1}.`

**Comment by thedillonb** [comment]
Is using `InvokeCommand` against a non-reactive command a large use case? It would seem like if you're using ReactiveUI you're trying to stay within the reactive family - just my assumption. Regardless, while the error message is definitely better than nothing, it seems silly to not use static checking to our advantage here. If the breakage is as big as you say, perhaps my suggestion should be altered to, instead of removing an override, create a new `InvokeReactiveCommand` extension with just `ReactiveCommand` arguments.

This, of course, is not a huge issue because I can create a version of `InvokeReactiveCommand` in my own app in 1 line of code. My concern is merely a quality of life one. I'd rather see ReactiveUI make it hard to write misbehaving apps and this linkage with `InvokeCommand` seems odd.

**Comment by kentcb** [comment]
Don't get me wrong - I 💯 agree with you. It's just that breaking changes like this are generally frowned upon. I personally don't use `ICommand` directly at all, but I can't speak for the community.

I was thinking along the same lines as you, except in reverse. Instead of `InvokeReactiveCommand` I was thinking `InvokeICommand`, but whatever. Regardless, it may be tricky to come to some consensus. In my experience, you can raise awareness through as many channels as you like (Slack, GitHub, Twitter) and many people don't notice until they update to that release, then they complain that their code has been broken by the update.

Let's see what feedback comes through on this. Thanks for raising it @thedillonb.
