### ISSUE TITLE
ObservableAsPropertyHelper needs to provide a way for users to determine if it's subscribed

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1491]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If you deferSubscribe, there is no way to know at current if there is a subscription later on.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**
To have a access method that allows access to the variable. 

**What is the motivation / use case for changing the behavior?**
It is costly for me with a large number of items (currently 200000+) to not use deferSubscription in my model/view model land to not to defer subscribe. I have a disposable in the OAPH and want to dispose if there has been a subscription only when doing a set operation. Having this accessor available will allow avoiding doing this work.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
All. I am using the latest 8.0 beta 89 for this bug.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
```csharp
    /// <summary>
    /// Returns if the ObservableAsPropertyHelper is subscribing to the 
    /// base Observable stream.
    /// </summary>
    public bool HasBeenSubscribed()
    {
        return (Interlocked.Read(ref _activated) == 1);
    }
```

I am going todo a pull request tonight.

**Comment by kentcb** [comment]
@glennawatson Just to be sure I understand the problem here: you have an `OAPH<IDisposable>` on your VMs and it is deferred. Upon cleaning up your VMs, you want to clean up that disposable resource _if it has been created_.

Is this correct?

If so, I agree in principal with your proposal. I _do_ think there may be more elegant ways to solve your problem, like a `DisposeMany` operator (as provided by DD I think):

```C#
this.someProperty = someObservable
    .Select(...)
    .DisposeMany()
    .ToProperty(..., defer: true);
```

Then you would just dispose `someProperty` when you dispose the VM. If the underlying subscription was never made, it's effectively a no-op. If it was made, then the `DisposeMany` will ensure proper clean-up of the resource in question. Moreover, the `DisposeMany` will ensure that each time the resource is created in response to `someObservable` ticking, the previous instance will be disposed. I think this might be a cleaner approach for you, but it's unfortunate that `DisposeMany` isn't built into Rx (you could just copy the source from DD though if you're not already using it - or did I write this myself at some point? Sorry, can't recall right now).

Anyway, it wouldn't hurt to include a subscription indicator as well, but I'd prefer it was a property called `IsSubscribed`.

**Comment by glennawatson** [comment]
Yeah the rationale behind the method vs the property, is it's not 100% trivial and generally I've had properties be trivial to make it obvious to the user something is happening 

You guys used the same design that seems to be on the ReactiveObject, but that may be because all the state is hosted elsewhere instead of in the actual base class itself.)

I will change to a property regardless.

**Comment by Asesjix** [comment]
@glennawatson  does the issue still exist, or can it be closed?

**Comment by glennawatson** [comment]
This was added in another pr a while back.
