### ISSUE TITLE
ReactiveCommand in current 8.0 alpha concurrency problem

### ISSUE THREAD

**Issue by SuperJMN** [reactiveui/ReactiveUI#1498]
PLEASE, reproduce the issue with this solution:

[WpfApp1.zip](https://github.com/reactiveui/ReactiveUI/files/1359134/WpfApp1.zip)

**Do you want to request a *feature* or report a *bug*?**
It's a bug

**What is the current behavior?**
The execution of the `Command` throws an InvalidOperationException related to concurrency.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Execute the attached demo (VS 2017 Preview and .NET 4.7.1, if possible, although it should fail in previous versions)

**What is the expected behavior?**

The `Command ` should execute without problems.

**What is the motivation / use case for changing the behavior?**

Well, it's simply the way a `ReactiveCommand `should behave. We simply expect it to work :)

**It works perfectly in the latest stable version.**

Please, check the question in Stack Overflow: https://stackoverflow.com/questions/46574940/reactiveui-command-concurrency-webclient

**Comment by kentcb** [comment]
Thanks for the repro, @SuperJMN. I've found that the problem is related to the (new) separation of WPF functionality from ReactiveUI core. Without the `reactiveui-wpf` package, you don't have the correct initialization logic for the platform. Thus, you end up with the `RxApp` ambient contexts incorrectly configured, including using the wrong schedulers. Those schedulers are not using the correct thread, so things go 💥 

By installing `reactiveui-wpf`, the problem is solved. I suspect there's something better we can do about the experience here, but I am unsure what it is just now. I'll open a separate issue to track.

**Comment by kentcb** [comment]
See #1499
