### ISSUE TITLE
Using reactiveui package without reactiveui-wpf has issues

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1499]
**Do you want to request a *feature* or report a *bug*?**

Experience bug.

**What is the current behavior?**

Installing only `reactiveui` into a WPF application leads to pain. The platform initialization logic is now in `reactiveui-wpf`, so failing to install that package means `RxApp` is not correctly initialized. This means incorrect schedulers will be used and things go 💥 whenever the UI is updated via `RxApp.MainThreadScheduler`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create a new WPF application.
2. Install only the `reactiveui` package.
3. Use `RxApp.MainThreadScheduler` to update a UI component.

**What is the expected behavior?**

Hard to say. Ideally, users would be told to install `reactiveui-wpf` (or "install a platform project"). However, I'm not sure that's practical because it _might_ be valid to install only `reactiveui` in some contexts...

**What is the motivation / use case for changing the behavior?**

Improve consumer experience.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

`8.0.0-alpha0094`

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by SuperJMN** [comment]
Now everything has an explanation!

**Comment by ghuntley** [comment]
Thoughts:

- This change is documented over at https://github.com/reactiveui/website/blob/master/input/docs/getting-started/installation/nuget-packages/index.md#windows-presentation-foundation
- We need to do a better job of advertising this change (it deserves its own section in the readme)
- People are going to keep falling into this trap because the behaviour/cheese has been moved and existing users may not know about this change
- `reactiveui@net45x` should now only be used for unit test libraries which have no need to update UI thread.
- Can we add some type of framework warning that checks the for the presence of `Windows.Presentation` without referencing it?

**Comment by Asesjix** [comment]
@kentcb does the issue still exist for you, or can it be closed?
Because in Visual Studio I can run the tests without error.

![test](https://user-images.githubusercontent.com/7798041/40023468-7f3ffd9a-57cb-11e8-9169-a77126de64e6.PNG)
?

**Comment by ghuntley** [comment]
Closed as v8 is out and this has been documented in release notes + website docs for the platform.
