### ISSUE TITLE
nameof() overload for ObservableAsPropertyHelper mixin. 

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1505]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

In the ObservableAsPropertyHelper MixIn's it currently has a option of only using Expression to get the property name we are interested in observing. In my own code I got a dramatic boost in speed by using the nameof() operator instead since you never really want to use a "sub-property". I want to add to the code base a overload that allows you to specify a string instead of the Expression. This was a massive speed boost in my Observation objects on a project I'm working on. Unlike in WhenAnyValue() where you can have sub-properties the motivation for using Expression (beyond being consistent with like the WhenAnyValue syntax) is not as strong. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**
Allow a overload to a string which is the propertyName. This allows the use of nameof() to avoid the runtime hit of Expression.

**What is the motivation / use case for changing the behavior?**
Performance. 

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
ReactiveUI 8

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
If people are happy to add a overload, I will provide a PR.

**Comment by kentcb** [comment]
This sounds good @glennawatson. Send in the PR!

As you say, parity across all RxUI operators isn't currently possible. However, I think the main reason is the internal reliance on the expression, not because of property chains. After all, we could always have overloads that take a `string[]` instead of an expression, where each `string` represents one property in the chain. Sound crazy? Not if you've got a Fody addon that rewrites all expression-based invocations as `string`-based invocations, which is something I could imagine being useful for OAPH once you provide the impl.
