### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by ShalokShalom** [reactiveui/ReactiveUI#1581]
**Do you want to request a *feature* or report a *bug*?**

Depends on what is the case.

**What is the current behavior?**

Your homepage speaks about support for all .Net platforms on the top and lacks to mention Linux on the bottom.

**What is the motivation / use case for changing the behavior?**

Suggest Linux support if not yet supported, clearance of the wording on the homepage if so.

**Comment by Qonstrukt** [comment]
ReactiveUI is heavily focussed on UI frameworks not on a platform per sé. You can use ReactiveUI with Xamarin Forms for example which means it'll work with every platform Forms supports.

I'm not sure which UI frameworks currently exist for .NET on Linux though. You have GTK#, but ReactiveUI doesn't add any features to it, and the question is if that's even worth the trouble.

Do you have any suggestions perhaps on where ReactiveUI could help development on Linux?

**Comment by ShalokShalom** [comment]
Yes, providing a Qt Quick binding.
This helps also to create applications for other platforms also, since Qt is very focused on cross platform deployment.

Seriously, I am wondering why you support so many different UI toolkits and exactly the most widespread one, with the highest coverage of both platforms and features is ignored? :slightly_smiling_face:

It supports GPU acceleration out of the box, WYSIWYG editing of your UI, then easy to change themes and so on.

Its the default language for the Plasma desktop from KDE and you can see here a comparison from one guy who ported from [GTK+ to Qt]( https://youtube.com/watch?v=ON0A1dsQOV0)

This way also implicitly separates UI code from logic code. 

Hope this helps ^-^

**Comment by tthiery** [comment]
I think there is no QT binding for .NET yet. The closest and modern Linux UI toolkit for .NET are the alpha stuff binding GTK via GTK# to Xamarin.Forms. once on Xamarin.Forms ReactiveUI is back in the game. Checkout https://GitHub.com/xamarin/Xamarin.Forms

**Comment by ShalokShalom** [comment]
https://github.com/ddobrev/QtSharp

**Comment by tthiery** [comment]
Oh cool. Well... Needs to go the xamarin forms road :) Thanks for giving me the link!

**Comment by ShalokShalom** [comment]
Why Xamarin?

**Comment by tthiery** [comment]
Comfort and Reuse for me via Xamarin.Forms. But for ReactiveUI I do not know the binding patterns of QtSharp.

**Comment by ShalokShalom** [comment]
So, how does that look like for us then?

**Comment by Qonstrukt** [comment]
Well someone should step up to build the support in RxUI, but it's often a chicken-and-egg story. Nearly no-one using ReactiveUI needs it apparently, so the chance of someone supporting / maintaining it currently, building that support is pretty small. They would at least need knowledge of the Qt framework to begin with.

What stops you from giving it a go actually? 😊 It's a serious question, because following your explanation that might attract a lot of new developer interest into ReactiveUI.
It doesn't need to be perfect from the start, it could be ongoing development. Heck, it might even interest some of the ReactiveUI maintainers in Qt.

But I think time is most often the reason such a thing is not easily started with...

**Comment by ShalokShalom** [comment]
To be honest: Qt supports ALL the platforms and is the most widespread and well known open source toolkit world wide.

Why do you prefer to maintain half a dozens of toolkits with half of the features?

I might understand this project incorrectly, since its still unclear to me what it does exactly. :slightly_smiling_face:

**Comment by Qonstrukt** [comment]
Honestly, then why are you interested in this project? You might know a lot of people that work with Qt, I know absolutely zero. You're the first. 😉 

Nobody here uses GTK on a daily basis as well. Most users came from or develop for Windows, and others a purely focussed on mobile.

I think there's not much to discuss here. If you want to implement Qt in ReactiveUI, take a shot, it's always welcome! But if your question is why it isn't integrated yet, then it's because none of the maintainers has had enough time and/or interest.

**Comment by ShalokShalom** [comment]
And if man power is in your interest, why spread it?

**Comment by tthiery** [comment]
@Qonstruct Thanks for your feedback. An unfortunate reality. My Hope is that the Xamarin.Forms GTK platform will catch some traction. But realistically that will not happen either.

**Comment by ShalokShalom** [comment]
[Luckily](https://www.youtube.com/watch?v=ON0A1dsQOV0)

**Comment by Infernno** [comment]
Sorry that I'm little bit late to the party

> [Avalonia](https://github.com/AvaloniaUI/Avalonia) is a WPF-inspired cross-platform XAML-based UI framework providing a flexible styling system and supporting a wide range of OSs: Windows (.NET Framework, .NET Core), Linux (GTK), MacOS, Android and iOS.

So it's seems to be possible to build UI apps with ReactiveUI & Avalonia on Linux.
