### ISSUE TITLE
Binding to ReactiveUserControl.ViewModel does not set the ViewModel

### ISSUE THREAD

**Issue by qrzychu** [reactiveui/ReactiveUI#1669]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I created ReactiveUserControl<Item>. It works well with ViewModelViewHost and so on.

I figured that I could use it on it's own in XAML like this:

<local:ItemView ViewModel="{Binding SelectedBigItem.Item}"/>
but it does not work - SelectedBigItem.Item is not displayed. The property SelectedBigItem does raise change notifications. Item itself is DTO - just plain properties.

I know two solutions:

Use ViewModelViewHost - seems like a huge overkill, since it will always display the same view

code behind subscription. I gave the control name = "ItemPreview" and in CB:

        IDisposable sub = null;
        sub = this.WhenActivated(d =>
        {
            ViewModel.WhenAnyValue(x => x.SelectedBigItem).Subscribe(quote =>
            {
                ItemPreview.ViewModel = quote?.Item;
            }).DisposeWith(d);

            sub.DisposeWith(d);
        });
both work and I hate both: one is an overkill, and second feels like cheating and is tedious. Why binding does not work? I tried setting different triggers and modes, but nothing helped.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

https://github.com/qrzychu/ReactiveUserControlBindingSample

I craeted quick sample. There are 3 ways of binding and the only one that does not work is through ViewModel.SelectedItem property.

        <local:ItemView DockPanel.Dock="Top" ViewModel="{Binding ElementName=List, Path=SelectedItem}"/> 

        <local:ItemView DockPanel.Dock="Top" ViewModel="{Binding SelectedItem}"/>

        <local:ItemView DockPanel.Dock="Top" x:Name="ItemView"/>
In the first commit you can see that it behaves exactly the same when there is no BigItem and just Item

Other commits represent different scenarios.

**What is the expected behavior?**

Control should display bound ViewModel

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

RxUI 8.2.1 + WPF

**Comment by glennawatson** [comment]
You probably need a Mode=OneWay in your binding. ViewModel={Binding SelectedItem, Mode=OneWay}, two way binding doesn't make sense in this context.

**Comment by Wouterdek** [comment]
Also, I think your WhenActivated code fragment will not work as you intend it to, and you probably would actually use something like this:
```Csharp
this.WhenActivated(d => d(
   this.WhenAnyValue(v => v.ViewModel.SelectedBigItem).Select(query => query?.Item).BindTo(this, v => v.ItemPreview.ViewModel)
));
```

**Comment by qrzychu** [comment]
Hi,

I've updated RxUI to 8.3.1 and nothing changed.

@glennawatson setting binding mode didn't do anything.

@Wouterdek my version does the job: sets new value. That's all I want - one way mode.

**Comment by Wouterdek** [comment]
Sorry, should have clarified. Here are a couple of details you might or might not have intended with your original code:

- In the WhenActivated block, you specify that the WhenActivated block itself should be disposed. This will break your view the first time the view is deactivated, because the WhenActivated block will not be called when the view is displayed again.
- You perform a WhenAnyValue on the ViewModel property. [Its not recommended to use WhenAny in this way.](https://reactiveui.net/docs/guidelines/framework/use-this-on-left-of-whenany) Not only for memory management reasons, but mostly because the viewmodel can change again without WhenActivated being retriggered, which means your binding would not update to the new viewmodel. Also, if the view is displayed before the viewmodel is assigned, ViewModel will be null and you will get a NullReferenceException.
- BindTo is the [recommended, idiomatic way](https://reactiveui.net/docs/handbook/when-any/#idiomatic-usage) to express bindings that cannot be expressed with a Bind or OneWayBind().

**Comment by qrzychu** [comment]
OK, I get it now. 

But I am still wondering how to achieve this in XAML, since in most cases it have to write the whole WhenActivated bit just for one line that I should be able to set in XAML.

As for disposing WhenAcitvated, I found that as answer somewhere on SO as a solution to firing this block more than once in WPF. It also fixes that sometimes it gets fired when the view is deactivated (especially when there is animation). 

It still works, since in most cases the views are recreated next time they are needed.
