### ISSUE TITLE
Router.NavigateBack Index Out of Range Error or view not loaded

### ISSUE THREAD

**Issue by davidcraddock** [reactiveui/ReactiveUI#1845]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
navigating forward and back by quickly clicking on the buttons produces an index out of range exception or the view fails to load

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Demo can be found here
https://github.com/davidcraddock/ReactiveUINavError

**What is the expected behavior?**
Should be able to navigate back and forth without exception 

**What is the motivation / use case for changing the behavior?**

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

WPF
.Net 4.7.1
ReactiveUI version 9.3.5
VS2017

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
![image](https://user-images.githubusercontent.com/19299305/48924895-8a629880-ef11-11e8-808a-1a2a2ebbfb7c.png)

**Comment by glennawatson** [comment]
Don't think it relates to your project directly but you should move from packages.config to PackageReference format https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

There is a wizard in Visual studio to convert now (you may need to make PackageReference your preferred format in the menu format).

There are a lot of bugs we receive due to people using the older format.

**Comment by glennawatson** [comment]
Unable to preproduce, I updated to the latest PackageReference so now your project just has a reference to ReactiveUI.WPF 9.4.1 and I click quite a bit and no crashes are happening.
