### ISSUE TITLE
[BUG] View Location does not set ComboBox.SelectionBoxItemTemplate

### ISSUE THREAD

**Issue by andrejpanjan** [reactiveui/ReactiveUI#1905]
**Describe the bug**
View Location does not set `ComboBox.SelectionBoxItemTemplate`, while `ComboBox.ItemTemplate` is set properly.

**Steps To Reproduce**
1. Create a `ViewModel` class.
2. Create a `View` class that derives from `ReactiveUserControl<ViewModel>`.
3. Create a list of `ViewModel`-s (`List<ViewModel> viewModelsList`).
4. Put a `ComboBox comboBox` in a new window.
5. Set `comboBox.ItemsSource =  viewModelsList`.
6. Run.
7. Select an item from `comboBox` dropdown list.
8. Selected item is not shown in the SelectionBox.

**Expected behavior**
Selected item should be shown it the SelectionBox using the same template that is used for the items in the dropdown list.

**Screenshots**
![image](https://user-images.githubusercontent.com/7609378/51099968-18e9ec80-17d4-11e9-885d-54c53bd86bfa.png)

**Environment:**
 - OS: Windows 10
 - ReactiveUI version: 9.8.1
- GUI framework: WPF

**Comment by glennawatson** [comment]
Also given your a contributor to our open collective your bug is going to the top of the triage. Hopefully we should have a fix ready soon.

**Comment by andrejpanjan** [comment]
It is WPF.

**Comment by gpriaulx** [comment]
I have gotten as far as I can with tracing this issue tonight, and will probably need to hand over or seek advice from someone with a deeper understanding of the `ViewModelViewHost`.

The problem is easy to reproduce, I have created a project demonstrating this (attached) that can either have the RxUI nuget packages added or remounted in the RxUI solution. 

The DataTemplate is applied. This can be seen by offering an alternative `IPropertyBindingHook` and providing a modified template:

```cs
const string template = "<DataTemplate xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' " +
                        "xmlns:xaml='clr-namespace:ReactiveUI;assembly=__ASSEMBLYNAME__'> " +
                        "<Border Background=\"Red\" Padding=\"10\"><xaml:ViewModelViewHost ViewModel=\"{Binding}\" VerticalContentAlignment=\"Stretch\" HorizontalContentAlignment=\"Stretch\" IsTabStop=\"False\" /></Border>" +
                        "</DataTemplate>";
```

The visible red padding when an item is selected highlights the template is in use, but the event sequence within the `ViewModelViewHost` instance appears different to the other instances. I am not familiar enough with this mechanism to say more, but am at the point of trying to make sense of the updates and the timing around those updates.

![comboboxtemplateissue](https://user-images.githubusercontent.com/8568379/51108980-e4b01380-1847-11e9-8f75-bb844cb334f9.png)

[TemplateIssueSample.zip](https://github.com/reactiveui/ReactiveUI/files/2754886/TemplateIssueSample.zip)

**Comment by cabauman** [comment]
Looks like you have to explicitly include the DataTemplate:

> Regular Binding will automatically work without a DataTemplate. It will generate a DataTemplate to display a string representation of the provided data.
> 
> RxUI bindings does not work that way; you have to provide a DataTemplate for them to work:

```
<ComboBox Name="Source">
    <ComboBox.ItemTemplate>
        <DataTemplate>
            <TextBlock Text="{Binding MyString}"/>
        </DataTemplate>
    </ComboBox.ItemTemplate>
</ComboBox>
```

I tried this out with the project @gpriaulx made and it seems to work.

**Comment by glennawatson** [comment]
Hmm. Our binding generated a data template automatically so it's a bug with that generation.

**Comment by gpriaulx** [comment]
The generation is working alright, it's the `ViewModelViewHost`. The generated `DataTemplate` is applied, but doesn't resolve/update the view accordingly.

**Comment by cabauman** [comment]
Looks like a disposal problem. I removed the WhenActivated from ViewModelViewHost and ExampleItemView.xaml.cs and everything works as expected.

**Comment by glennawatson** [comment]
No it's a legitimate bug with the ViewModelViewHost and the Combobox in WPF land

Essentially if a ItemTemplate is set and it's a ContentControl (which ViewModelViewHost is) it'll call into https://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/ComboBox.cs,871

It will then grab the Item from the control, set the ItemTemplate for a new hosted control, and then set the ViewModel to be the previous View set on the control.

Just fixing it now.

**Comment by glennawatson** [comment]
@andrejpanjan That should be fixed now. https://www.nuget.org/packages/reactiveui/9.8.9

**Comment by andrejpanjan** [comment]
@glennawatson Yes, it is. Thank you.
