### ISSUE TITLE
[BUG] Failed to resolve service for type "..." always shown

### ISSUE THREAD

**Issue by albilaga** [reactiveui/ReactiveUI#1918]
**Describe the bug**
Failed to resolve service for type "..." always shown when using `ViewLocator.ResolveView`

**Steps To Reproduce**
1. Open this sample https://github.com/albilaga/RxNavigationTest
2. Click button `Go To Page 2`
3. See Application Output
4. It will showing error message Failed to resolve service for type "..."  even though the view have no problem to be created

**Expected behavior**
When view have successfully created, warning message not to be shown

**Environment(please complete the following information):**
 - OS:Android & iOS (checked, not checking other platform yet)

**Comment by glennawatson** [comment]
This problem is located in https://github.com/reactiveui/ReactiveUI/blob/master/src/ReactiveUI/View/DefaultViewLocator.cs

Basically the method `private IViewFor AttemptViewResolution(string viewTypeName, string contract)` needs to only one have the error message for the catched exception, but all the Log().Debug() need to disappear. 

Then we will only warn the user in the public method `public IViewFor ResolveView<T>(T viewModel, string contract = null)` towards the end.

**Comment by glennawatson** [comment]
@ajpinedam is going to have a look into this one. Thanks @ajpinedam  and @albilaga  for reporting it.

**Comment by glennawatson** [comment]
Fixed by #1935
