### ISSUE TITLE
ReactiveUI.XamForms xaml design not render in VS2019 xaml previewer

### ISSUE THREAD

**Issue by csharpq** [reactiveui/ReactiveUI#1998]
Hi, 

I am working on mobile application using Xamarin.Forms and ReactiveUI, and noticed that the UI design is not rendering in XAML previewer using visual studio 2019.

See attach screenshot. Thanks. :)

![Capture](https://user-images.githubusercontent.com/12070151/55940440-ba1cfd80-5c72-11e9-8bb6-c6ce860d7685.PNG)

**Comment by glennawatson** [comment]
This is an issue with any view class that has a "x:TypeArguments" inside of it not just from ReactiveUI.

**Comment by glennawatson** [comment]
Going to close this issue since it's more of a Microsoft xaml issue. Pain I know.

**Comment by tenninebt** [comment]
> Hi,
> 
> I am working on mobile application using Xamarin.Forms and ReactiveUI, and noticed that the UI design is not rendering in XAML previewer using visual studio 2019.
> 
> See attach screenshot. Thanks. :)
> 
> ![Capture](https://user-images.githubusercontent.com/12070151/55940440-ba1cfd80-5c72-11e9-8bb6-c6ce860d7685.PNG)

Have you found a solution to this issue? Maybe you logged a bug/issue at Xamarin repo? (Link?)
Thanks

**Comment by glennawatson** [comment]
Would recommend opening one if you want to persue it with Microsoft. Lodging a bug in our repo does not automatically start one with theirs.

**Comment by tenninebt** [comment]
@glennawatson We know, but at least 2 people ended up here (Probably more would have come here if the issue contained the error message in text format instead of image), it was worth asking if anyone did anything about it (Log a bug, find a workaround...), before going further or create duplicates. But I understand your point.

Anyway, so after some research, adding the following attribute `[DesignTimeVisible(true)]` to the view class (`UserInfoView`) seems to do the trick.
Works with VS2019 Mac Preview version (8.1 Preview 2306), and in the current stable (8.0.5 build 9).
Hope it helps.

**Comment by glennawatson** [comment]
Awesome. If it keeps your issue resolved will add stuff to the docs.
