### ISSUE TITLE
[BUG] 'The current thread has no Dispatcher associated with it.' on unit Test with xUnit 2.4.1 and ObserveOnDispatcher

### ISSUE THREAD

**Issue by Taliesin60** [reactiveui/ReactiveUI#2075]
**Describe the bug**
When the test constructor of xUnit create a ViewModel with SourceList and ObserveOnDispatcher method, I take an exception `The current thread has no Dispatcher associated with it.`.

**Steps To Reproduce**
1. Create an UnitTest using xUnit 2.4.1
2. in the ctor, make a ViewModel which use ObserveOnDispatcher
4. We take an error : `The current thread has no Dispatcher associated with it.`

**Expected behavior**
The ViewModel is created and test continues execution

**Environment**
- OS:       Windows
- Version   10
- Device:   Personnal Computer

**Additional context**
- DynamicData : 6.9.1.2588
- ReactiveUI : 9.16.4

**Comment by glennawatson** [comment]
Using `RxApp.MainThreadScheduler` should solve your issue, see https://reactiveui.net/docs/handbook/scheduling/ for further details.

Also see https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/threading-model -- by default dispatchers are a UI related thing, so if you want to run it on a non-UI based application you have to create a dispatcher and run the event loop yourself.

This wouldn't be a bug just expected behaviour.
