### ISSUE TITLE
[BUG] .net core WPF WeakEventManager

### ISSUE THREAD

**Issue by adampanger** [reactiveui/ReactiveUI#2230]
Hi there,

With the possibility to use netcoreapp3.0 as the target framework for WPF apps, the WeakEventManager issue is back. 

[#661](https://github.com/reactiveui/ReactiveUI/issues/661)
[#1617 (Workaround)](https://github.com/reactiveui/ReactiveUI/issues/1617)

As I see, that WeakEventManager is disabled for WPF with net4 directives, however with .net core, netcoreapp3 can be WPF, too. With the workaround above, everything looks fine.

**Comment by ronaldvdv** [comment]
I can confirm this issue occurs in WPF on .NET Core 3 (and 3.1). I believe where we check for NET_461 we should also test for NETCOREAPP3_0 to solve this problem. Unfortunately I'm not familiar enough with the ReactiveUI source code to test these changes myself (adding the NETCOREAPP3_0 conditions in itself is not too hard).

**Comment by ronaldvdv** [comment]
Just tested the workaround from #1617 in my own repository and this solves the problem as well, so I believe the solution to the issue is indeed as suggseted above.

**Comment by glennawatson** [comment]
I think the weak event manager was attempting to solve issues on wpf in the first place and then it got turned off for that platform. I am going to investigate removing it all together

**Comment by bawkee** [comment]
I agree that there's probably no point adding (and maintaining) preprocessor directives to turn off a feature on a platform for which it was specifically made in the first place. It all started with a change in #547.  It solves some problems that are due to how WPF consumes events and inadvertently leaks memory - the purpose of weak event pattern is to fix exact such problems. But using it for property changed events from within view models seems not to be a good idea.... I have had some bindings on view X stop after some GC only after view Y has done something like inserting an item to an observable collection. It's the worst kind of problem, no log, exception or anything unfortunately.

**Comment by glennawatson** [comment]
This is fixed as part of #2276

**Comment by ronaldvdv** [comment]
Thanks a lot! :-)
