### ISSUE TITLE
RaisePropertyChanged() causes app to hang

### ISSUE THREAD

**Issue by travbid** [reactiveui/ReactiveUI#2414]
**Describe the bug**
Regression after updating ReactiveUI from 11.3.1 to 11.4.1  

Sorry, this is difficult to describe. My WPF app now reliably hangs when calling `RaisePropertyChanged()` under certain conditions. I created the most minimal, complete example I could demonstrating the behaviour (https://github.com/travbid/reactiveui-bug).   

The app hangs at line 18 of `Example.WPF/MainWindowViewModel.cs` and becomes unresponsive. If I remove the call to `.ConfigureAwait(false)` on line 31 it works as expected.

**Steps To Reproduce**
```bash
git clone https://github.com/travbid/reactiveui-bug
cd reactiveui-bug
git submodule update --init
dotnet run --project Example.WPF/Example.WPF.csproj
```
**Expected behavior**
The App moves from a red screen to a blue screen without anything locking up.

**Environment**
- OS: Windows 10

**Comment by glennawatson** [comment]
Ah thanks for providing that sample. It will make it much easier to diagnose.

**Comment by WalkerCodeRanger** [comment]
There is a thread deadlock. The sequence is:

1. A worker thread runs `this.RaisePropertyChanged(nameof(this.IsUserAuthenticated));`
2. That ends up calling OnNext of the property changed observable `_propertyChanged.Value.OnNext(changed);`
3. Inside reactive extensions, it acquires several locks
4. The subscribed event ends up calling the view model property change handler
5. That calls `Application.Current.Dispatcher.Invoke(...)` which blocks the worker thread waiting for the invoke to complete.
6. The main thread then executions the lambda passed to invoke
7. That sets `this.mainFrame.Content = page;`
8. Which triggers `this.mainFrame.Navigating += (o, e) => ViewModel.ClearMenu();` to fire
9. That ends up setting `MainWindowViewModel.MenuItems`
10. Which tried to raise another property changed event on the main window view model
11. That then goes through the same property changed observables and needs to acquire the same locks as are held by the worker thread.
12. The worker thread is blocked waiting on the main thread holding several locks. The main thread must acquire those locks before it can make progress. Deadlock.

The reason removing `.ConfigureAwait(false)` on line 31 makes it work is it causes the initial raise of the event to occur on the main thread. When the second property change fires it is still on the main thread. Since locks are reentrant, it is able to enter the lock again from the main thread and everything goes as expected.

My recommendation would be to use `await Application.Current.Dispatcher.InvokeAsync(...)` instead of `Application.Current.Dispatcher.Invoke(...)`. That prevents this deadlock and in general should be a better way do to things.

However, I'm going to continue working on this issue. If someone with more experience with advanced Rx.net than me has any suggestions for avoiding these kinds of deadlocks I'd appreciate the input. It seems like issues like this should have come up with Rx.net before. There is a risk of deadlocks like this anytime an observer sends another value to the observable.

**Comment by travbid** [comment]
Omg this is amazing. Thank you @WalkerCodeRanger

**Comment by quinmars** [comment]
Yes, please, remove the `.ConfigureAwait`. It may not be required by WPF but it makes your live much more easier, when you treat the view model with thread affinity, i.e., only state changes (including emitting events) on the main thread.

**Comment by anaisbetts** [comment]
The bug here is in step #1, ViewModels that are bound in any way to a View (even indirectly) must only be accessed on the UI thread

**Comment by WalkerCodeRanger** [comment]
@anaisbetts I'm somewhat new to using ReactiveUI with WPF, but I thought it was ok to update ViewModels bound to view from non-UI threads in WPF. Isn't that why WPF automatically marshalls change events to the UI thread for you? Is there a resource that gives the guideline not to and discusses the reasoning behind it? I'd like to understand better.

**Comment by anaisbetts** [comment]
>  Isn't that why WPF automatically marshalls change events to the UI thread for you?

I don't recall WPF doing this! The reason that ReactiveUI doesn't do this for you is because:

- Doing this would *not* make your ViewModels thread-safe, just "kinda thread safe". This means that we would turn easy-to-fix crashes into impossible-to-solve corruption and Weird Issues. Easy to fix is much better!

- Marshaling every update is extremely laggy and expensive, any large application would grind to a halt (ironically doing mostly nothing!) if we did this. Every tick of the thread loop in WPF adds ~100-200ms of latency, a few OAPHs later and you're up to _seconds_ of lag.
