### ISSUE TITLE
OneWayBind Null Value throws

### ISSUE THREAD

**Issue by stokara** [reactiveui/ReactiveUI#2476]
OneWayBind throws an error when the value is null

The vm has a reactiveProperty called appointment which itself has a reactive DateTime property Canceled

this.OneWayBind(ViewModel, vm => vm.Appointment.Canceled, v => v.CanceledDateTime.Text, dt => dt?.ToString("G"));

compiles but at runtime when vm.Appointment.Canceled is null  throws System.ArgumentNullException
message: Value cannot be null.
Parameter name: paramValue

It looks like BindToDirect,(PropertyBinderImplementation.cs line 322) is looking for a setter, but it is a oneWayBind so there is no setter

Changing to Bind gets around the problem:
            this.Bind(ViewModel, vm => vm.Appointment.Canceled, v => v.CanceledDateTime.Text, dt => dt?.ToString("G"), s=> s == "" ? (DateTime?) null : DateTime.Parse(s));

**Environment**
- OS:       Windows 10, WPF
- Version   11.5.6

This behavior works as expected, i. e. The bound value can be null when using OneWayBind in version 11.4.17

**Comment by cabauman** [comment]
Can you include which version you upgraded from?

**Comment by CyLuGh** [comment]
I guess I can see the same thing in my project.

> PropertyBinderImplementation: v.TextBlockResult.Text Binding received an Exception! - System.ArgumentNullException: Value cannot be null. (Parameter 'paramValue')
   at ReactiveUI.PropertyBinderImplementation.<>c__DisplayClass10_0`3.<BindToDirect>g__SetThenGet|0(Object paramTarget, Object paramValue, Object[] paramParams) in d:\a\1\s\src\ReactiveUI\Bindings\Property\PropertyBinderImplementation.cs:line 322
   at ReactiveUI.PropertyBinderImplementation.<>c__DisplayClass10_0`3.<BindToDirect>b__7(<>f__AnonymousType0`2 x) in d:\a\1\s\src\ReactiveUI\Bindings\Property\PropertyBinderImplementation.cs:line 353
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 48

I'm a bit shameful at showing my first real open source project, but you can find it here: https://gitlab.com/CyLuGh/hierarchygrid/-/tree/rxui_11.5

If you run the demo project, click on fill, then resize the window, you should see plenty of messages complaining in the console.
And the value displayed aren't correct anymore: 
https://i.imgur.com/5QaNO6Q.png 
https://i.imgur.com/9HNsik8.png

The grids should be the same, I recycle the views and viewmodels when I redraw my component. As the first binding is ok, I think it's the update to a null value that causes the trouble.

Master branch is still in 11.4.17 and works fine.

Typing all that has given me an idea to maybe reproduce the problem is a small scope project, I'll start that right away.

**Comment by cabauman** [comment]
Thank you. I'm going to push a fix for one of the other bind issues very soon, which looks like it's caused by the exact same thing. So I may not have to try your project out. I'll leave another comment asking you to confirm the fix.

**Comment by CyLuGh** [comment]
Meanwhile, I've created a much smaller project: https://github.com/CyLuGh/rxui-11.5

`this.OneWayBind(vm, vm => vm.Data,  v => v.SampleTextBlock.Text, s => s?.UnimportantText)`

If the binded object is null, the binding will break and won't ever be updated again.
