### ISSUE TITLE
[BUG] Enabling nullable reference types causes ReactiveContentPage to error

### ISSUE THREAD

**Issue by grierson** [reactiveui/ReactiveUI#2551]
**Nullable causes ReactiveContentPage to error**

Reopening #2330 

Created a ReactiveContentPage and enabled Nullable reference types causes

`MainPage.xaml.cs(5, 26): [CS0263] Partial declarations of 'MainPage' must not specify different base classes`

**Steps To Reproduce**

1. Created sample project to reproduce issue. https://github.com/grierson/Sandbox
2. Try to build the project.
3. Error

**Expected behavior**

For the project to run.

**Environment**

- ReactiveUI: 11.5.35
- ReactiveUI.XamForms: 11.5.35
- Xamarin.Forms: 4.8.0

**Additional context**

Use ReactiveContentPage for ReactiveUI.Validation binding

**Comment by glennawatson** [comment]
This one is likely a wpf or dotnet bug. You'll have to lodge the bug with them about the nullability issue.

**Comment by glennawatson** [comment]
One suggestion

https://github.com/grierson/Sandbox/blob/99acf158da82e070602cdd75b8ba35666a0c5911/Sandbox/Sandbox/MainPage.xaml.cs#L5

Remove the base type declaration in your c# file. It's not needed and redundant due to it being a partial class. 

It's likely due to the view model being nullable which makes sense since you won't have the view model always set all the time.

**Comment by glennawatson** [comment]
This is by design and not a bug. We make the view models property nullable.
