### ISSUE TITLE
[BUG] this.RaiseAndSetIfChanged does not trigger PropertyChanged event for generic IReactiveObject

### ISSUE THREAD

**Issue by timothylcooke** [reactiveui/ReactiveUI#2594]
**Describe the bug**
If a custom `IReactiveObject` (in this example, `IReactiveObjectFilter`) calls `this.RaiseAndSetIfChanged(ref _field, value)`, then `RaisePropertyChanging` and `RaisePropertyChanged` methods are never called, and therefore `PropertyChanging` and `PropertyChanged` events are not triggered. 

While `IReactiveObjectFilter.WhenAnyValue(x => x.ShouldFilter)` receives notifications when `this.RaiseAndSetIfChanged` is called, `SourceList<IReactiveObjectFilter>.Connect().AutoRefresh(x => x.ShouldFilter)` does not receive notifications, since `PropertyChanged` is never called.

**Steps To Reproduce**
[`https://github.com/timothylcooke/IReactiveObjectExample.git`](https://github.com/timothylcooke/IReactiveObjectExample.git) demonstrates the behavior. This is a WPF project that shows a window with a `TabControl`. Both Tabs shows a `MyUserControl`. Each `MyUserControl` has a binding to a `MyViewModel`, which has a `SourceList<IFilter>` of filters (toggled with the CheckBoxes). In the first tab, the `IFilter` objects are `ReactiveObjectFilter` objects, and in the second tab, the `IFilter` objects are `IReactiveObjectFilter` objects. Whether the `IFilter` extends `ReactiveObject` or implements `IReactiveObject` determines if the `PropertyChanged` event is triggered, and therefore if the `SourceList<IFilter>.Connect().AutoRefresh(x => x.ShouldFilter)` triggers updates.

**Expected behavior**
If I implement `IReactiveObject` and call `this.RaiseAndSetIfChanged()`, it should call `RaisePropertyChanged`.

**Screenshots**
In the screenshots below, the key difference is that in the first screenshot, where the `IFilter` objects inherit from `ReactiveObject`, we see the line `Filter… PropertyChanged("ShouldFilter") fired.` This ripples down and ends up triggering `filtersSource.Connect().AutoRefresh(x => x.ShouldFilter)`, and in turn updates the `currentFilters` collection. In the second screenshot, where the `IFilter` objects implement `IReactiveObject`, `PropertyChanged` is never called on the filter, and therefore `filtersSource.Connect().AutoRefresh(x => x.ShouldFilter)` is never fired. This leaves our `currentFilters` collection unmodified, and therefore does not filter any items in the Filtered Names list.

![image](https://user-images.githubusercontent.com/8904110/101491827-37aa7c80-3932-11eb-9b12-13a1667a5541.png)
![image](https://user-images.githubusercontent.com/8904110/101492013-688ab180-3932-11eb-8a60-44e565c992f1.png)

**Environment**

- OS:       Windows 10 Pro x64
- Version   ReactiveUI 12.1.5
- Device:   Dell XPS 13 9360

**Additional context**
N/A

**Comment by glennawatson** [comment]
I'll have a look at this one after I get my massive .net 5 branch sorted. 

Will do it as part of a Fody refactor I did a while back and get that in.

**Comment by glennawatson** [comment]
Also thanks for providing the sample, that always helps.

**Comment by timothylcooke** [comment]
I just added screenshots of the sample app. I figured that's easier to see than cloning and debugging.

> Also thanks for providing the sample, that always helps.

You're welcome. I can't tell you how many "bugs" I've identified in various libraries where I try to make a sample project to reproduce it, find that I can't, and eventually realize it's not a bug and I'm doing something stupid in my main project. I always feel better about reporting something if I can reproduce it in a simple project.

P.S. I'm still fairly new to Dynamic Data, so I hope you'll forgive me if some of my observables are less than optimal.

**Comment by bruzkovsky** [comment]
Hi, I have the same problem after upgrading to 11.5.35 from 10.5.43

**Comment by bruzkovsky** [comment]
@glennawatson @RLittlesII can I be of any help with fixing this?

This issue is pressing for us, because after updating to ReactiveUI 13.3.1 none of the Xamarin Forms bindings that go directly to the PageViewModel are working. This is because we use MvvmCross, and they require us to extend `MvxViewModel`, so we had to implement `IReactiveObject` in those view models ourselves. Now, it looks like you are requiring us to extend `ReactiveObject` too, which is not possible (no multiple inheritance in C#). So the only thing that works is using Rx bindings where there are no `PropertyChanged` events fired (interestingly, that works). But that's not a permanent solution, I think you'd agree.

When I look at the `ReactiveObject` implementation, it seems the following line is needed to enable propagation of `PropertyChanged` events - if I read the execution flow correctly.

https://github.com/reactiveui/ReactiveUI/blob/92df299fadf768a01eadd435e29d7cdf95cc015f/src/ReactiveUI/ReactiveObject/ReactiveObject.cs#L45

This is the implementation of the extension method:

https://github.com/reactiveui/ReactiveUI/blob/92df299fadf768a01eadd435e29d7cdf95cc015f/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs#L215-L221

Here is the implementation in `IReactiveObjectExtensions.ExtensionState` (called in line 220):

https://github.com/reactiveui/ReactiveUI/blob/92df299fadf768a01eadd435e29d7cdf95cc015f/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs#L365

And finally, where the event should be propagated (line 375 checks if the Lazy was created with `SubscribePropertyChangedEvents`):

https://github.com/reactiveui/ReactiveUI/blob/92df299fadf768a01eadd435e29d7cdf95cc015f/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs#L367-L385

I assume that simply calling `SubscribePropertyChangedEvents` would be enough, but it's internal. What was the idea behind that decision / can we make an easy fix and turn this method public?

**Comment by glennawatson** [comment]
Looking through it you should be able to make those public. The rationale was due to it accessing a internal state object but it should abstract it for you.

It's a breaking change but we have some changes to binding coming that are breaking so now would be a good time for you to make these changes.

**Comment by bruzkovsky** [comment]
Thanks for the quick reply, I'll fire up a PR!

**Comment by timothylcooke** [comment]
For the benefit of anybody who stumbles across this issue in the future, from the commit notes for commit 4f94c6b6afd3fcf998bb0a78719582e164a5ca8e, we have:

> This change enables consumers to implement `IReactiveObject` and get `PropertyChanged` and `PropertyChanging` notifications (which regressed in version 11.4.1) to get the notifications, one must call `this.SubscribePropertyChangedEvents()` or `this.SubscribePropertyChangingEvents()` on the `IReactiveObject` instance
