### ISSUE TITLE
[BUG] Wpf net5 - When setting the ViewModel prop, the DataContext is null

### ISSUE THREAD

**Issue by BrayanKhosravian** [reactiveui/ReactiveUI#2836]
**Describe the bug**

When I inherit from ReactiveWindow<T> and set the `ViewModel` property, then the DataContext remains `null` and the view does not load the bindings.

When I set the `DataContext` then the `ViewModel` property is null.

I am not sure, but I guess this also happens with other base types as ReactiveControl<T>.
Created a simple repo and zipped it.

**Steps To Reproduce**
[Playground.WPF.zip](https://github.com/reactiveui/ReactiveUI/files/6880790/Playground.WPF.zip)

In the App.xaml.cs file I am setting the property.

**Expected behavior**
Both DataContext and the VIewModel property should be the instance of the viewmodel.

**Screenshots**

![image](https://user-images.githubusercontent.com/35541212/127050864-d8bf85ef-44b3-4cf1-a1ee-89de24211c9b.png)

**Environment**
Frameworks and Libraries: 
- .NET 5 Wpf
- ReactiveUi 14.1.1
- ReactiveUi.WPF 14.1.1

- OS:         Windows 10
- Version   10.0.19042 Build 19042
- Device:   Dell Inspiron 15

**Additional context**

**Question**:  Is this intended to work like this? I mean, I would expect that the DataContext is not null when the ViewModel property is set.
I also know that this happens when using xaml bindings.
It is also possible to workaround this by implementing IViewFor for a custom ReactiveWindow and all other controls.

But imo, the current situation disables the use of xaml bindings and forces the user to either write bloat or use code behind bindings instead of xaml bindings.>

What do you think?

**Comment by BrayanKhosravian** [comment]
example of the extra code which has to be written.
Lets ignore the fact that i didt use a dependency property.
```cs
public class RxWindow<TViewModel> : Window, IViewFor<TViewModel>
		where TViewModel : ReactiveObject
	{
		public TViewModel ViewModel 
		{ 
			get => (TViewModel)DataContext;
			set => DataContext = value;; 
		}

		object IViewFor.ViewModel 
		{
			get => ViewModel;
			set => ViewModel = (TViewModel)value; 
		}


	
	}

```

**Comment by glennawatson** [comment]
This is intentional and not a bug.

**Comment by glennawatson** [comment]
If you are using rxui binding binding conrext is not a required concept. 

Users also have the ability to set it if they are using xaml binding

**Comment by BrayanKhosravian** [comment]
Do you mean that the user should set both properties if required?
eg.
```cs
var vm = new Vm();
var view = new View();

view.DataContext = vm;
view.ViewModel = vm;

```

**Comment by glennawatson** [comment]
Well first way we push is not to have a binding context since it's not needed by our binding engine. 

You can do it in the xaml though and then xaml designers are aware of the type

On the root node

`DataContext="{Binding RelativeSource={RelativeSource Self},  Path=ViewModel}"/>`

That solution means that xaml editors like visual studios or rider are aware of the type and will provide xaml intellisense while the code behind will not

**Comment by BrayanKhosravian** [comment]
ok this is interesting.
 because i have always used this for intellisesne support:  `d:DataContext="{d:DesignInstance Type=mainVm:MainViewModel}"`
 while reimplementing IViewFor<T> for all components.
 I think type awareness in xaml and xaml.cs is important imo.

**Comment by BrayanKhosravian** [comment]
I mean, after u posted this, i think something like this should also be possible
`ViewModel="{Binding RelativeSource={RelativeSource Self}, Path=DataContext}"/>`
not tried yet ofc

**Comment by ChrisPulman** [comment]
DataContext="{Binding RelativeSource={RelativeSource Self}, Path=ViewModel}" is used for designtime and runtime.

**Comment by ChrisPulman** [comment]
In the code behind then set the ViewModel to your instance either using a Dependency Resolver or by seting it to a new instance of your viewmodel.

**Comment by ChrisPulman** [comment]
You can also do `DataContext = ViewModel = new MainViewModel();` in the code behind and `d:DataContext="{d:DesignInstance Type=mainVm:MainViewModel}"` in the xaml

**Comment by glennawatson** [comment]
Sounds like you want binding at runtime regardless.

The problem with setting DataContext/ViewModel all at the same time won't cater for the scenario where ViewModel changes or vice versa (whichever way you want to do it)

**Comment by ChrisPulman** [comment]
I have personally used WPF since 2006, using XAML based bindings has caused many issues almost all of which go undetected. By using ReactiveUI code bindings this makes your code more reliable, testable and easier to maintain. There are somethings that just have to be done in XAML, but wherever possible try to use reactiveUI bindings. Initially it may go against the grain of what you may have been taught, but once you start working on large scale applications you will be thankful for choosing the ReactiveUI way of doing MVVM.
I understand that many of the examples on the internet show the use of the DataContext, but very few of the applications I work on use this binding method, unless I am forced to use XAML bindings for some very specific reason.

If you did not yet join our Slack ReactiveUI group please do there are many people there who can offer you support in developing ReactiveUI based applications. https://www.reactiveui.net/slack 

Welcome to ReactiveUI and I hope that you enjoy working with ReactiveUI as much as I have over the past 10 years
