### ISSUE TITLE
[BUG] BindCommand with parameter

### ISSUE THREAD

**Issue by RomanSoloweow** [reactiveui/ReactiveUI#2904]
When using BindCommand with a parameter, like:

```C#
BindCommand (ViewModel,
   x => x.MyCommand,
   x => x.KeyBinding,
   x => x.MyProperty).DisposeWith (disposable);
```

The parameter will be initialized once. That is the parameter will remain the same even if the MyProperty is updated.
Expected Behavior: Execute an expression "withParameter" every time a command is executing

**Comment by ChrisPulman** [comment]
Thanks for raising this issue, we will investigate shortly.
What is the Type of MyProperty so that we can test and resolve.

**Comment by ChrisPulman** [comment]
I have found where the issue is and am working on a fix.

**Comment by ChrisPulman** [comment]
Whilst looking at trying to fix this I discovered that it is working as expected but has some requirements that need to be met to function correctly. The PR attached above fixes the tests related to this functionality but then proves it has the ability to operate as required.

In this example please ensure that Viewmodel is initialised prior to creating the Binding. 
This is due to the Expression being compiled when the binding is created. 
The ViewModel must be part of the view passed to the left of the BindCommand for the expression to capture updates from the parameter. The parameter must be part of the ViewModel and also be initialised at the time the binding is created.
```
this.ViewModel = new();
this.ViewModel.MyProperty = new();
this.BindCommand(ViewModel,
   x => x.MyCommand,
   x => x.KeyBinding,
   x => x.MyProperty).DisposeWith (disposable);

```
I trust that this fits with your requirements, otherwise please post a Repo that we can assist you in getting working.

**Comment by RomanSoloweow** [comment]
When I tried it with IObservableList - I was getting an empty collection but replacing IObservableList with ReadOnlyObservableCollection worked.

 Thank you so much for your work
