### ISSUE TITLE
[BUG] RxApp.MainThreadScheduler not acting as expected on Xamarin/UWP

### ISSUE THREAD

**Issue by Thorocaine** [reactiveui/ReactiveUI#3017]
**Describe the bug**
On all versions after 15.1.1  When I use `.ObserveOn(RxApp.MainThreadScheduler)` Subscribe does not run on the UI thread.
This is causing the application to crash as soon as anything updates a value bound to UI.

**Steps To Reproduce**
Update Reactive UI to any version after 15.1.1  
I have also created a [repo ](https://github.com/Thorocaine/RxUiTest)to show the problem.

**Expected behaviour**
I expect any code in a subscription, after `.ObserveOn(RxApp.MainThreadScheduler)` to run on the Main Thread.

**Environment**
- OS:          Windows 11
- Version:   Dev
- Device:    Ausus Laptop (Intel)
- ReactiveUI Version:    16.3.10

**Comment by glennawatson** [comment]
There was a change due to winui where uwp now has a new package `reactiveui.uwp`. You'll need to install that nuget package

Let me know if that resolved the issue

**Comment by Thorocaine** [comment]
That did work, and I feel silly now 😣

Thank you for the very fast response.

**Comment by tebeco** [comment]
For anyone that just lost 1 hours in "issue game" (because closed and locked)

https://github.com/reactiveui/website/issues/646
https://github.com/reactiveui/ReactiveUI/issues/2993
https://github.com/reactiveui/ReactiveUI/pull/2999

As much as I understand that closed issue is hard to track ... it does not mean they should be locked
That obliterate the possibility for individual from the community to raise their hands informing that in fact only a portion of the issue was fixed and either
* re-open it => a PR merged does not mean the full issue is fixed
* allow post tracking
* unsubscribe / auto unsubscribe from closed issue

**Comment by glennawatson** [comment]
Our policy is to lock old issues. No apologies in regards to this.

**Comment by glennawatson** [comment]
There are many repositories including dotnet who close old issues. It's industry standard. Doesn't stop you from reading the issues and solving the issue like you have done.
