### ISSUE TITLE
[Bug]: got imcompatible message when using with .net 7

### ISSUE THREAD

**Issue by anthtoonaing** [reactiveui/ReactiveUI#3645]
### Describe the bug 🐞

I am using .net 7.0. When I add ReactiveUI.WinForm (19.5.1) to project, I got this message.

Package 'ReactiveUI.WinForms 19.5.1' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0-windows7.0'. This package may not be fully compatible with your project.

Application can run.

### Step to reproduce

1. Create a .net 7.0 WinForm project.
2. Add ReactiveUI.WinForm to project.
3. Warning message will see under ReactiveUI.WinForms package in SolutionExplorer->Dependencies->Packages.

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

This should happen...

**Comment by glennawatson** [comment]
System.Reactive (a downstream dependency of ours) requires for windows the TargetFramework in the csproj to be `net7.0-windows10.0.19041` or later windows SDK.

`<TargetFramework>net7.0-windows10.0.19041</TargetFramework>`

The theory why they lock in a later version is because net7-windows is a much earlier version of the SDK so you don't get bug fixes. Having a later SDK does not prevent you from targetting earlier versions of windows.
