### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aurax** [reactiveui/ReactiveUI#3728]
### Describe the bug 🐞

Hello,
I can't use the latest few versions of ReactiveUI.WPF because not suitable version is listed in the nuget package.

The "net6.0-windows" target framework name is used in my C# project like this:
```
<PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
</PropertyGroup>
```

This target framework name prevents updating to the latest version of the ReactiveUI.WPF (19.5.41) because the nuget package provides a list of exact targets (which don't match my settings) like:

```
<dependencies>
...
  <group targetFramework="net6.0-windows10.0.17763">
    <dependency id="ReactiveUI" version="19.5.31" exclude="Build,Analyzers" />
  </group>
  <group targetFramework="net6.0-windows10.0.19041">
    <dependency id="ReactiveUI" version="19.5.31" exclude="Build,Analyzers" />
  </group>
...
</dependencies>
```

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

I think the dependencies should use a common target version or could you please add the target name "net6.0-windows".

### Screenshots 🖼️

![image](https://github.com/reactiveui/ReactiveUI/assets/1779282/c64b4441-8c11-4c4d-8286-45db2cfc0934)

### IDE

Visual Studio 2022

### Operating system

Windows

### Version

11

### ReactiveUI Version

19.5.41

### Additional information ℹ️

```
Restoring packages for C:\work\projects\abc.csproj...
  GET https://api.nuget.org/v3/vulnerabilities/index.json
  OK https://api.nuget.org/v3/vulnerabilities/index.json 74ms
  GET https://api.nuget.org/v3-vulnerabilities/2024.02.06.05.41.26/vulnerability.base.json
  GET https://api.nuget.org/v3-vulnerabilities/2024.02.06.05.41.26/2024.02.08.05.41.44/vulnerability.update.json
  OK https://api.nuget.org/v3-vulnerabilities/2024.02.06.05.41.26/vulnerability.base.json 19ms
  OK https://api.nuget.org/v3-vulnerabilities/2024.02.06.05.41.26/2024.02.08.05.41.44/vulnerability.update.json 68ms
NU1701: Warning As Error: Package 'ReactiveUI.WPF 19.5.41' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0-windows7.0'. This package may not be fully compatible with your project.
Package restore failed. Rolling back package changes for 'abc'.
Time Elapsed: 00:00:00.4501848
========== Finished ==========
```

**Comment by dpvreony** [comment]
this is due to dependencies in System.Reactive along with the default targeting of netX-windows being windows 7 which is unsupported

the recommendation is to target net6.0-windows10.0.19041

**Comment by aurax** [comment]
> this is due to dependencies in System.Reactive along with the default targeting of netX-windows being windows 7 which is unsupported
> 
> the recommendation is to target net6.0-windows10.0.19041

Strange...
please, check, for example, the "Microsoft.VisualStudio.Threading" NuGet package references. They supports net6.0-windows7.0 target.
```
<dependencies>
    <group targetFramework=".NETFramework4.7.2">...</group>
    <group targetFramework="net6.0">...</group>
    <group targetFramework="net6.0-windows7.0">...</group>
    <group targetFramework=".NETStandard2.0">...</group>
</dependencies>
```

**Comment by ChrisPulman** [comment]
If you were to purely add System.Reactive to a WPF Application with a net8.0-windows TFM you will find yourself with a net462 version of the assembly trying to be added to your project, due to some conflicts this will then lead to incorrect System.Reactive elements being used in your application, ultimately leading to instabilities within your application.
ReactiveUI.WPF has a dependency on System.Reactive and hence we must use their minimum supported windows version in order to have full support for the underlying functions.
We strongly recommend that you follow these guidelines to ensure optimum performance and support. You should always base your minimum on the newest supported windows version within the dependencies included in your application.
Different TFM's have differences in the functionality included, often a newer TFM will be selected to make use of a particular feature.
I hope that you can understand this, many thanks and we hope that you can enjoy using ReactiveUI for your projects.
