### ISSUE TITLE
Extend WhenAnyValue with a filter

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#625]
I often find myself stumped by the following code

```
var o = this.WhenAny(p=>p.A, p=>p.B, (a,b)=>Foo(a,b));
```

or using method directly

```
var o = this.WhenAny(p=>p.A,p=>p.B, Foo);
```

However often in a viewmodel the properties are initialized as **null** and in this case the method **Foo** will crash with a **NullReferenceException**. The RX way to handle this is

```
var o = this.WhenAny(p=>p.A, p=>p.B
                  , (a,b)=>new {a,b})
                  .Where(o=>o.a!=null && o.b!=null)
                  .Select(o=>Foo(o.a,o.b);
```

which seems to be quite a bit of boiler plate plus the added garbage of an anonymous type. It would be nice to be able to do

```
var o = this.WhenAny(p=>p.A, p=>p.B
              , (a,b)=>a!=null && b!=null
              , Foo)
```

 or even sweeter

```
var o = this.WhenAnyNotNull(p=>p.A, p=>p.B, Foo);
```

This just happens enough to me that a special case for filtering nulls in view models would be appreciated.

**Comment by kentcb** [comment]
Firstly, I don't think this makes sense because `WhenAny` _never_ returns `null` - it can potentially return `IObservedChange<T>` with a `null` value. Perhaps you meant `WhenAnyValue`?

I would consider it more intuitive to be able to omit the selector, which results in an `IObservable<Tuple<...>>`:

```cs
this
    .WhenAnyValue(x => x.A, x => x.B)
    .Where(x => x.Item1 != null && x.Item2 != null)
    .Subscribe(Foo);
```

That said, I'm not really convinced this is necessary and warrants the extra complication of yet more overloads, but perhaps I'm missing something.

**Comment by bradphelan** [comment]
Actually omitting the selector is a better idea with one extra thing.  Add
overloads of Where and Select which can destructure tuples.

this
    .WhenAnyValue(x => x.A, x => x.B)
    .Where((a,b) => a != null && b != null)

      .Select((a,b) => a + b)

    .Subscribe(Foo);


However there are proposals in c# 7 to do native tuple destructuring which
may assist.

**Comment by kentcb** [comment]
Closing as I believe this is covered by #1316.
