### ISSUE TITLE
Support for Fody PropertyChanged and PropertyChanging

### ISSUE THREAD

**Issue by systemsymbiosis** [reactiveui/ReactiveUI#812]
Fody PropertyChanged and PropertyChanging have served me well for the last few years and help keep the view models clean. The latest releases of ReactiveUI appears to break the ability of Fody to weave the required code. The issue is documented on the Fody Repo here

https://github.com/Fody/PropertyChanged/issues/105#issuecomment-75908245 

Is there something that can be changed in ReactiveUI to make this work?

**Comment by SimonCropp** [comment]
@paulcbetts  do you want a PR for this?

**Comment by SimonCropp** [comment]
@Haacked i am waiting on a response from paul

**Comment by paulcbetts** [comment]
I'm not super excited to make huge changes to this system, especially in ReactiveUI 6.x. We can redo them for RxUI 7.x. If you want to make a proposal as to how to change it and make sure it works on every platform without introducing memory leaks, I'd certainly look at it, but that seems Like A Lot Of Work

**Comment by SimonCropp** [comment]
@paulcbetts i kind of suspected you made the methods explicit for reasons. But can you explain how a inherited class calling the onpropchanged method can result in a mem leak? just trying to understand.

**Comment by paulcbetts** [comment]
@SimonCropp Basically the whole goal of this complicated code is similar to WeakEventManager, where we're trying to not hold onto references even though technically we should because the developer was lazy and didn't disconnect things. Here's some PRs to read: 

* https://github.com/reactiveui/ReactiveUI/pull/689
* https://github.com/reactiveui/ReactiveUI/pull/448
* https://github.com/reactiveui/ReactiveUI/pull/432

**Comment by SimonCropp** [comment]
I suspected as much. however I still dont understand how having a onpropchanged being explicit prevents a mem leak. 

it seems here https://github.com/reactiveui/ReactiveUI/pull/448#issuecomment-36480028  it was made explicit because you felt it is "wrong" rather than any thing related to memory. Can you elaborate on "wrong"

Even if this is not ideal doesnt it unfairly constrain the api. for example I have had many users (of propertychanged.fody) want to raise multiple propchange events from a single set. this is useful in certain readonly property scenarios.

**Comment by paulcbetts** [comment]
> for example I have had many users (of propertychanged.fody) want to raise multiple propchange events from a single set.

This is something you *have* to do in other MVVM frameworks, but is explicitly Very Incorrect™ to do in ReactiveUI. It's not incorrect in Fody's case since you're using it for Good and not Evil, but having the method there encourages people to do wrong things.

**Comment by SimonCropp** [comment]
ok that is fair enough. Since i dont want to force bad practices into ReactiveUI I will instead change Fody to do an explicit cast so it is compat with ReactiveUI .

So u can close this

**Comment by SimonCropp** [comment]
thanks for taking the time to explain

**Comment by systemsymbiosis** [comment]
Yes thanks Paul. And thanks Simon for chasing up and proposing a fix from the Fody side. Appreciated 100%

**Comment by distantcam** [comment]
The explicit methods for invoking PropertyChanged are not hooked up to the observables, so they don't work with methods like `WhenAny` for example.

I created a repo that has the issue. https://github.com/distantcam/ReactiveUI6Issue

It looks like the work-around is to create a base class that implements an `OnPropertyChanged` and use that with PropertyChanged.fody

**Comment by shiftkey** [comment]
I've not had a chance to look into it, but https://github.com/kswoll/ReactiveUI.Fody seems to be promising. cc @kswoll

**Comment by kswoll** [comment]
I wrote it for a Xamarin.iOS project I'm working on at my company.  My colleague found a bug yesterday when using auto-property initializers.  Other than that, seems to be working well for us so far.  If you use it, let me know if you run into any trouble.
