### ISSUE TITLE
Activation/Loaded fires twice.

### ISSUE THREAD

**Issue by chuuddo** [reactiveui/ReactiveUI#816]
I make some cool stuff with TabControl and ViewModelViewHost. All works fine, but when i switch to another tab, happens this:

```
TabAView unloaded.
TabBView loaded.
TabAView loaded.
TabAView unloaded.
```

If it's OK, can you explain why this is happening or where I made a mistake?

All test code here
https://github.com/chuuddo/ReactiveUIActivation
I tested it without reactiveui:

```
TabAView unloaded.
TabBView loaded.
```

https://github.com/chuuddo/ReactiveUIActivation/tree/withoutreactiveui

**Comment by llifon** [comment]
Everything below is in reference to ReactiveUI with WPF (.NET 4.5).

I seem to experiencing many issues regarding WhenActivated (and Loaded) being fired multiple times inside the view (not but not in the view-model). This happens in all forms of views and is really bugging me.

As for the tab issue, which I've also been dealing with since I started adopting ReactiveUI, I developed my own work-around. I have view-models that I use for tabs which own an IsActive property. I toggle this property when I change the tab. Using a custom content template on the TabControl, I null the ViewHost ViewModel when a tab isn't active. I can't really tell you why it works, but hopefully it will give you guys some insight.

This stops multiple activation / loaded calls and works great as a work-around for tab controls. Unfortunately I cannot apply this to other "views" so I'm still stuck with multiple WhenActivated / Loaded events in random areas of my code (I mainly use Routing for navigation).

            <TabControl.ContentTemplate>
                <DataTemplate>

                    <reactiveUi:ViewModelViewHost x:Name="ViewHost"
                                                  ViewModel="{Binding}"
                                                  HorizontalContentAlignment="Stretch"
                                                  VerticalContentAlignment="Stretch">
                    </reactiveUi:ViewModelViewHost>

                    
                    <DataTemplate.Triggers>
                        <DataTrigger Binding="{Binding IsActive}" Value="False">
                            <Setter TargetName="ViewHost" Property="ViewModel" Value="{Binding}" />
                        </DataTrigger>
                        <DataTrigger Binding="{Binding IsActive}" Value="True">
                            <Setter TargetName="ViewHost" Property="ViewModel" Value="{Binding}" />
                        </DataTrigger>
                    </DataTemplate.Triggers>
                </DataTemplate>
            </TabControl.ContentTemplate>
