### ISSUE TITLE
MainThreadScheduler and TaskPoolScheduler not set to CurrentThreadScheduler in unit tests

### ISSUE THREAD

**Issue by flagbug** [reactiveui/ReactiveUI#854]
Using RxUI 6.5.0 in a NET45 unit test project, the RxApp  schedulers are set to `WaitForDispatcherScheduler` and `TaskPoolScheduler` even though we're in a unit test.

Splat's `ModeDetector.InUnitTestRunner` returns `true` btw.

**Comment by frogger3d** [comment]
I'm also having troubles with the default schedulers. The difference is that while running tests in debug mode calling the getter on RxApp.MainThreadScheduler causes an InvalidOperationException:

    Exception thrown: 'System.InvalidOperationException' in System.Reactive.Windows.Threading.dll

    Additional information: The current thread has no Dispatcher associated with it.

I'm using VS2015, RxUI 6.5.0 and Splat 1.6.2.

**Comment by csmager** [comment]
I've just come across this. The issue seems to be the `[ThreadStatic]` for `_UnitTestMainThreadScheduler` (and the same argument for `TaskPoolScheduler`).

On registration, `MainThreadScheduler` is set to `WatiForDispatcherScheduler`, which will go via the property setter [here](https://github.com/reactiveui/ReactiveUI/blob/rxui6-master/ReactiveUI/RxApp.cs#L91), setting both the `_MainThreadScheduler` and `_UnitTestMainThreadScheduler` fields.  The getter will return `_UnitTestMainThreadScheduler` if it has a value.

The initialisation, however, only sets the `_MainThreadScheduler` value to `CurrentThreadScheduler`.  So `MainThreadScheduler` will return `WaitForDispatcherScheduler` for that thread - which, I think, depending on your unit test runner, could be for every test.

**Comment by solarplexus6** [comment]
I'm also getting an InvalidOperationException, because there's no check [here](https://github.com/reactiveui/ReactiveUI/blob/rxui6-master/ReactiveUI/Platform/Registrations.cs#L72) whether it's executing in a unit test runner. There's no DispatcherScheduler.Current in NUnit tests runner. It seems there's no workaround for this.

**Comment by cabauman** [comment]
Resolved by #2496
