### ISSUE TITLE
Nuke ViewContractAttribute

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#880]
This attribute is of questionable utility. Unless there are objections, kill it with :fire:

**Comment by kentcb** [comment]
Fixed by #914

**Comment by moswald** [comment]
I missed this issue back when it was filed. I only just noticed it because I've just migrated to the v7 branch.

I use this attribute in several places.

```csharp
[ViewContract(Contract = "Detailed")]
class MyDetailedView : IViewFor<MyViewModel>
```
```csharp
[ViewContract(Contract = "Summary")]
class MySummaryView : IViewFor<MyViewModel>
```

**Comment by kentcb** [comment]
@moswald: I'm a little confused because the only code I removed checks for `ViewContractAttribute` on the VM, not the view. That's why I raised this in Slack: because it seemed rather pointless.

How is your attribute being consumed? Are you perhaps resolving it yourself in your registration logic?

**Comment by moswald** [comment]
I agree it was misapplied in the past, since the contract shouldn't come from the VM itself, but rather from whatever is trying to resolve the V for that VM. I've been sitting on [this PR](https://github.com/reactiveui/ReactiveUI/pull/1013) for a bit. :)

I'll go ahead and close this, as that PR will fix it assuming it's accepted.
