### ISSUE TITLE
RoutedViewHost issues on iOS 64

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#967]
Just realized the bug fixes and enhancements I've made to the iOS `RoutedViewHost` have not made their way back to RxUI. Just creating this issue so I don't forget. I'll flesh it out with details when I get to it.

**Comment by PureWeen** [comment]
Is this version checked in anywhere? I checked your fork and it doesn't look like it...

Can I try it out?   :-)   The RoutedViewHost has been a bit quirky for me curious to see what you've fixed and enhanced..

For example the current one double navigates on startup.... If you run the playground project it puts two TestViews on the stack because there are two observables watching Router.Navigate that fire on initialization..   I was going to create an issue for it but if that's one of the things you've resolved then I'll just leave it...

**Comment by PureWeen** [comment]
wait wait NM I'm probably talking about a different RoutedViewHost ... The one in the Xamarin Forms projects... I'll create a separate issue for that one

**Comment by kentcb** [comment]
This was fixed by #1086.
