### ISSUE TITLE
Unexpected behavior of Command.CanExecuteObservable

### ISSUE THREAD

**Issue by jack128** [reactiveui/ReactiveUI#970]
```c#
var cmd = ReactiveCommand.Create(Observable.Return(true));
cmd.CanExecuteObservable.Subscribe(x => MessageBox.Show(x.ToString()));
MessageBox.Show("End of story");
```
This code returns
```
False
True
End of story
```
I belive "False" is very stange value. Or its by design?
Note, in test mode - "False" disappears

Simple workaround
```c#
        public static IObservable<bool> CanExecuteObservableFix(this ICommand command)
        {
            return Observable.Create<bool>(obs =>
            {
                obs.OnNext(command.CanExecute(null));
                return Observable.FromEventPattern(
                    handler => command.CanExecuteChanged += handler,
                    handler => command.CanExecuteChanged -= handler)
                    .Select(_ => command.CanExecute(null)).Subscribe(obs);
            });
        }
```

**Comment by flagbug** [comment]
This is "by design"

At line https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/ReactiveCommand.cs#L328 you'll notice the `StartWith(false)` method, which explains why you're seeing `false` as first value

As to why this behavior isn't the same in unit tests: At this line https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/ReactiveCommand.cs#L343 we're immedietaly connecting the observable, if you're in a unit test runner, so the first value is lost

I can understand why this behavior is confusing though
